-- Physical realization of the desired architecture for this repository revision.
--
-- This file may name source artifacts, symbols, workflows, jobs, and provider
-- operations. It binds the logical architecture to the current implementation.

INSERT INTO artifact(artifact_id) VALUES
  ('.github/workflows/codex-closed-loop.yml'),
  ('.github/workflows/disposable-agent-proof.yml'),
  ('.github/workflows/distributed-authority-chaos.yml'),
  ('.github/workflows/distributed-authority-handoff.yml'),
  ('.github/workflows/github-object-transport-proof.yml'),
  ('.github/workflows/operator-project-advance.yml'),
  ('.github/workflows/operator-project-submit.yml'),
  ('.github/workflows/production-criticality-mutation-probe.yml'),
  ('.github/workflows/production-latency.yml'),
  ('.github/workflows/promote-criticality-mutation-evidence.yml'),
  ('.github/workflows/substrate-capability-admission-treatment.yml'),
  ('.github/workflows/substrate-capability-admission.yml'),
  ('src/authority/engine.ts'),
  ('src/authority/facts.ts'),
  ('src/authority/project-state.ts'),
  ('src/authority/replay.ts'),
  ('src/authority/store.ts'),
  ('src/authority/transaction-admission.ts'),
  ('src/digest.ts'),
  ('src/effect-release-witness.ts'),
  ('src/observation/observe.ts'),
  ('src/providers/github/certified-status.ts'),
  ('src/providers/github/comment-attestation.ts'),
  ('src/providers/github/pr-update-branch-effect.ts'),
  ('src/providers/github/status-effect.ts'),
  ('src/providers/kubernetes/configmap-effect.ts'),
  ('src/source/source-integration.ts'),
  ('src/semantics.ts'),
  ('src/storage/git-store.ts'),
  ('test/digest-pure.test.ts'),
  ('test/projection-reconstruction.test.ts'),
  ('test/projector-pure.test.ts'),
  ('test/provider-observation.test.ts'),
  ('test/github-comment-attestation.test.ts'),
  ('test/trusted-effect-core-loop.test.ts');

INSERT INTO symbol(symbol_id, artifact_id) VALUES
  ('canonicalDigest', 'src/digest.ts'),
  ('validateAuthorityFact', 'src/authority/facts.ts'),
  ('deriveProjectProjection', 'src/authority/project-state.ts'),
  ('observePostcondition', 'src/observation/observe.ts'),
  ('KernelCore.claim', 'src/authority/engine.ts'),
  ('KernelCore.acquireExecution', 'src/authority/engine.ts'),
  ('KernelCore.authorizeEffect', 'src/authority/engine.ts'),
  ('KernelCore.beginEffect', 'src/authority/engine.ts'),
  ('KernelCore.performEffect', 'src/authority/engine.ts'),
  ('KernelCore.releaseEffectReservation', 'src/authority/engine.ts'),
  ('KernelCore.resolve', 'src/authority/engine.ts'),
  ('replayProjection', 'src/authority/replay.ts'),
  ('DurableFactStore.head', 'src/authority/store.ts'),
  ('DurableFactStore.append', 'src/authority/store.ts'),
  ('DurableFactStore.history', 'src/authority/store.ts'),
  ('mutationAdmitted', 'src/authority/transaction-admission.ts'),
  ('validateEffectReleaseEvidence', 'src/effect-release-witness.ts'),
  ('settlementSemantics', 'src/semantics.ts'),
  ('GitFactStore.head', 'src/storage/git-store.ts'),
  ('GitFactStore.append', 'src/storage/git-store.ts'),
  ('GitFactStore.history', 'src/storage/git-store.ts'),
  ('observationVerified', 'src/observation/observe.ts'),
  ('integrateVerifiedSourceCandidate', 'src/source/source-integration.ts'),
  ('observeCertifiedGitHubCommitStatus', 'src/providers/github/certified-status.ts'),
  ('observeCertifiedGitHubIssueCommentAttestation', 'src/providers/github/comment-attestation.ts'),
  ('performGitHubCommitStatusEffect', 'src/providers/github/status-effect.ts'),
  ('performGitHubPullRequestUpdateBranchEffect', 'src/providers/github/pr-update-branch-effect.ts'),
  ('performKubernetesConfigMapEffect', 'src/providers/kubernetes/configmap-effect.ts');

INSERT INTO symbol_implements_authority(symbol_id, authority_id) VALUES
  ('KernelCore.claim', 'project-authority'),
  ('KernelCore.acquireExecution', 'execution-authority'),
  ('KernelCore.authorizeEffect', 'effect-authority');

INSERT INTO symbol_implements_capability(symbol_id, capability_id) VALUES
  ('canonicalDigest', 'canonical-content-identity'),
  ('validateAuthorityFact', 'durable-project-facts'),
  ('replayProjection', 'durable-project-facts'),
  ('GitFactStore.head', 'durable-project-facts'),
  ('GitFactStore.append', 'durable-project-facts'),
  ('GitFactStore.history', 'durable-project-facts'),
  ('deriveProjectProjection', 'project-lifecycle-projection'),
  ('observePostcondition', 'authoritative-observation'),
  ('observationVerified', 'authoritative-observation'),
  ('KernelCore.authorizeEffect', 'effect-authorization'),
  ('mutationAdmitted', 'effect-authorization'),
  ('KernelCore.beginEffect', 'effect-reservation'),
  ('validateEffectReleaseEvidence', 'effect-reservation'),
  ('KernelCore.performEffect', 'effect-execution'),
  ('KernelCore.releaseEffectReservation', 'effect-release'),
  ('KernelCore.resolve', 'effect-settlement'),
  ('settlementSemantics', 'effect-settlement'),
  ('integrateVerifiedSourceCandidate', 'source-integration'),
  ('performGitHubCommitStatusEffect', 'github-commit-status-mutation'),
  ('observeCertifiedGitHubCommitStatus', 'github-commit-status-observation'),
  ('observeCertifiedGitHubIssueCommentAttestation', 'judgment-attestation-observation');

INSERT INTO symbol_projects_capability(symbol_id, capability_id) VALUES
  ('deriveProjectProjection', 'durable-project-facts'),
  ('deriveProjectProjection', 'effect-reservation'),
  ('deriveProjectProjection', 'effect-settlement');

INSERT INTO symbol_performs_effect(symbol_id, effect_id) VALUES
  ('performGitHubCommitStatusEffect', 'github-commit-status/create'),
  ('performGitHubPullRequestUpdateBranchEffect', 'github-pull-request/update-branch'),
  ('performKubernetesConfigMapEffect', 'kubernetes-configmap/ensure'),
  ('integrateVerifiedSourceCandidate', 'source/integrate');

INSERT INTO symbol_dispatches_to_symbol(symbol_id, implementation_symbol_id) VALUES
  ('DurableFactStore.head', 'GitFactStore.head'),
  ('DurableFactStore.append', 'GitFactStore.append'),
  ('DurableFactStore.history', 'GitFactStore.history');

INSERT INTO artifact_witnesses_evidence(artifact_id, evidence_id) VALUES
  ('test/digest-pure.test.ts', 'canonical-content-identity-proof'),
  ('test/projection-reconstruction.test.ts', 'projection-reconstruction-proof'),
  ('test/projector-pure.test.ts', 'projection-reconstruction-proof'),
  ('test/provider-observation.test.ts', 'provider-observation-proof'),
  ('test/github-comment-attestation.test.ts', 'judgment-attestation-proof'),
  ('test/trusted-effect-core-loop.test.ts', 'effect-core-loop-proof');

-- Hosted assurance evidence realization.
-- These rows describe what can invalidate evidence; workflows only decide how to execute it.
INSERT OR IGNORE INTO artifact(artifact_id) VALUES
  ('.github/workflows/authority-flow-analysis.yml'),
  ('.github/workflows/authority-storage-decomposition.yml'),
  ('.github/workflows/distributed-authority-chaos.yml'),
  ('.github/workflows/distributed-authority-handoff.yml'),
  ('.github/workflows/substrate-capability-admission-treatment.yml'),
  ('.github/workflows/substrate-capability-admission.yml'),
  ('architecture/concepts.sql'),
  ('architecture/logic.sql'),
  ('architecture/physics.sql'),
  ('experiments/authority-flow-analysis/analyzer.ts'),
  ('experiments/authority-flow-analysis/experiment.ts'),
  ('experiments/authority-storage-decomposition/contender.ts'),
  ('experiments/authority-storage-decomposition/experiment.ts'),
  ('experiments/authority-storage-decomposition/split-store.ts'),
  ('experiments/distributed-authority-chaos/controller.ts'),
  ('experiments/distributed-authority-handoff/controller.ts'),
  ('experiments/substrate-capability-admission/admission.ts'),
  ('experiments/substrate-capability-admission/experiment.ts'),
  ('experiments/substrate-capability-admission/fixtures.json'),
  ('experiments/substrate-capability-admission/hosted-evidence.ts'),
  ('scripts/plan-assurance-evidence.ts'),
  ('scripts/plan-hosted-evidence.ts'),
  ('src/architecture/change-planner.ts'),
  ('src/architecture/sql-model.ts'),
  ('src/authority/admission.ts'),
  ('src/authority/delegation.ts'),
  ('src/authority/engine.ts'),
  ('src/authority/facts.ts'),
  ('src/authority/interaction-frontier.ts'),
  ('src/authority/judgment-frontier.ts'),
  ('src/authority/project-agent-protocol.ts'),
  ('src/authority/project-graph.ts'),
  ('src/authority/project-intent.ts'),
  ('src/authority/project-state.ts'),
  ('src/authority/realization-reuse.ts'),
  ('src/authority/realization.ts'),
  ('src/authority/replay.ts'),
  ('src/authority/store.ts'),
  ('src/authority/transaction-admission.ts'),
  ('src/execution/confinement/hostile_worker.rs'),
  ('src/execution/confinement/main.rs'),
  ('src/execution/confinement/manifest.rs'),
  ('src/execution/confinement/proof.sh'),
  ('src/execution/confinement/resource.rs'),
  ('src/execution/confinement/resource_probe.rs'),
  ('src/execution/confinement/sandbox.rs'),
  ('src/execution/confinement/supervisor_proof.ts'),
  ('src/execution/confinement/x32_probe.rs'),
  ('src/providers/github/pr-update-branch-effect.ts'),
  ('src/providers/github/status-effect.ts'),
  ('src/source/transaction-planner.ts'),
  ('src/storage/git-kernel.ts'),
  ('src/storage/git-store.ts');

INSERT INTO artifact_witnesses_evidence(artifact_id, evidence_id) VALUES
  ('.github/workflows/authority-flow-analysis.yml', 'authority-flow-proof'),
  ('experiments/authority-flow-analysis/experiment.ts', 'authority-flow-proof'),
  ('.github/workflows/authority-storage-decomposition.yml', 'authority-storage-proof'),
  ('experiments/authority-storage-decomposition/experiment.ts', 'authority-storage-proof'),
  ('.github/workflows/distributed-authority-handoff.yml', 'distributed-authority-handoff-proof'),
  ('experiments/distributed-authority-handoff/controller.ts', 'distributed-authority-handoff-proof'),
  ('.github/workflows/distributed-authority-chaos.yml', 'distributed-authority-chaos-proof'),
  ('experiments/distributed-authority-chaos/controller.ts', 'distributed-authority-chaos-proof'),
  ('.github/workflows/substrate-capability-admission.yml', 'substrate-capability-admission-proof'),
  ('.github/workflows/substrate-capability-admission-treatment.yml', 'substrate-capability-admission-proof'),
  ('experiments/substrate-capability-admission/experiment.ts', 'substrate-capability-admission-proof'),
  ('experiments/substrate-capability-admission/hosted-evidence.ts', 'substrate-capability-admission-proof');

INSERT INTO evidence_depends_on_artifact(evidence_id, artifact_id) VALUES
  ('authority-flow-proof', '.github/workflows/authority-flow-analysis.yml'),
  ('authority-flow-proof', 'architecture/concepts.sql'),
  ('authority-flow-proof', 'architecture/logic.sql'),
  ('authority-flow-proof', 'architecture/physics.sql'),
  ('authority-flow-proof', 'experiments/authority-flow-analysis/analyzer.ts'),
  ('authority-flow-proof', 'experiments/authority-flow-analysis/experiment.ts'),
  ('authority-flow-proof', 'scripts/plan-assurance-evidence.ts'),
  ('authority-flow-proof', 'scripts/plan-hosted-evidence.ts'),
  ('authority-flow-proof', 'src/architecture/change-planner.ts'),
  ('authority-flow-proof', 'src/architecture/sql-model.ts'),
  ('authority-flow-proof', 'src/authority/engine.ts'),
  ('authority-flow-proof', 'src/providers/github/pr-update-branch-effect.ts'),
  ('authority-flow-proof', 'src/providers/github/status-effect.ts'),
  ('authority-flow-proof', 'src/source/transaction-planner.ts'),
  ('authority-storage-proof', '.github/workflows/authority-storage-decomposition.yml'),
  ('authority-storage-proof', 'architecture/concepts.sql'),
  ('authority-storage-proof', 'architecture/logic.sql'),
  ('authority-storage-proof', 'architecture/physics.sql'),
  ('authority-storage-proof', 'experiments/authority-storage-decomposition/contender.ts'),
  ('authority-storage-proof', 'experiments/authority-storage-decomposition/experiment.ts'),
  ('authority-storage-proof', 'experiments/authority-storage-decomposition/split-store.ts'),
  ('authority-storage-proof', 'scripts/plan-assurance-evidence.ts'),
  ('authority-storage-proof', 'scripts/plan-hosted-evidence.ts'),
  ('authority-storage-proof', 'src/architecture/change-planner.ts'),
  ('authority-storage-proof', 'src/architecture/sql-model.ts'),
  ('authority-storage-proof', 'src/authority/admission.ts'),
  ('authority-storage-proof', 'src/authority/delegation.ts'),
  ('authority-storage-proof', 'src/authority/engine.ts'),
  ('authority-storage-proof', 'src/authority/facts.ts'),
  ('authority-storage-proof', 'src/authority/interaction-frontier.ts'),
  ('authority-storage-proof', 'src/authority/judgment-frontier.ts'),
  ('authority-storage-proof', 'src/authority/project-agent-protocol.ts'),
  ('authority-storage-proof', 'src/authority/project-graph.ts'),
  ('authority-storage-proof', 'src/authority/project-intent.ts'),
  ('authority-storage-proof', 'src/authority/project-state.ts'),
  ('authority-storage-proof', 'src/authority/realization-reuse.ts'),
  ('authority-storage-proof', 'src/authority/realization.ts'),
  ('authority-storage-proof', 'src/authority/replay.ts'),
  ('authority-storage-proof', 'src/authority/store.ts'),
  ('authority-storage-proof', 'src/authority/transaction-admission.ts'),
  ('authority-storage-proof', 'src/source/transaction-planner.ts'),
  ('authority-storage-proof', 'src/storage/git-kernel.ts'),
  ('authority-storage-proof', 'src/storage/git-store.ts'),
  ('distributed-authority-chaos-proof', '.github/workflows/distributed-authority-chaos.yml'),
  ('distributed-authority-chaos-proof', 'architecture/concepts.sql'),
  ('distributed-authority-chaos-proof', 'architecture/logic.sql'),
  ('distributed-authority-chaos-proof', 'architecture/physics.sql'),
  ('distributed-authority-chaos-proof', 'experiments/distributed-authority-chaos/controller.ts'),
  ('distributed-authority-chaos-proof', 'scripts/plan-assurance-evidence.ts'),
  ('distributed-authority-chaos-proof', 'scripts/plan-hosted-evidence.ts'),
  ('distributed-authority-chaos-proof', 'src/architecture/change-planner.ts'),
  ('distributed-authority-chaos-proof', 'src/architecture/sql-model.ts'),
  ('distributed-authority-chaos-proof', 'src/authority/admission.ts'),
  ('distributed-authority-chaos-proof', 'src/authority/delegation.ts'),
  ('distributed-authority-chaos-proof', 'src/authority/engine.ts'),
  ('distributed-authority-chaos-proof', 'src/authority/facts.ts'),
  ('distributed-authority-chaos-proof', 'src/authority/interaction-frontier.ts'),
  ('distributed-authority-chaos-proof', 'src/authority/judgment-frontier.ts'),
  ('distributed-authority-chaos-proof', 'src/authority/project-agent-protocol.ts'),
  ('distributed-authority-chaos-proof', 'src/authority/project-graph.ts'),
  ('distributed-authority-chaos-proof', 'src/authority/project-intent.ts'),
  ('distributed-authority-chaos-proof', 'src/authority/project-state.ts'),
  ('distributed-authority-chaos-proof', 'src/authority/realization-reuse.ts'),
  ('distributed-authority-chaos-proof', 'src/authority/realization.ts'),
  ('distributed-authority-chaos-proof', 'src/authority/replay.ts'),
  ('distributed-authority-chaos-proof', 'src/authority/store.ts'),
  ('distributed-authority-chaos-proof', 'src/authority/transaction-admission.ts'),
  ('distributed-authority-chaos-proof', 'src/source/transaction-planner.ts'),
  ('distributed-authority-chaos-proof', 'src/storage/git-kernel.ts'),
  ('distributed-authority-chaos-proof', 'src/storage/git-store.ts'),
  ('distributed-authority-handoff-proof', '.github/workflows/distributed-authority-handoff.yml'),
  ('distributed-authority-handoff-proof', 'architecture/concepts.sql'),
  ('distributed-authority-handoff-proof', 'architecture/logic.sql'),
  ('distributed-authority-handoff-proof', 'architecture/physics.sql'),
  ('distributed-authority-handoff-proof', 'experiments/distributed-authority-handoff/controller.ts'),
  ('distributed-authority-handoff-proof', 'scripts/plan-assurance-evidence.ts'),
  ('distributed-authority-handoff-proof', 'scripts/plan-hosted-evidence.ts'),
  ('distributed-authority-handoff-proof', 'src/architecture/change-planner.ts'),
  ('distributed-authority-handoff-proof', 'src/architecture/sql-model.ts'),
  ('distributed-authority-handoff-proof', 'src/authority/admission.ts'),
  ('distributed-authority-handoff-proof', 'src/authority/delegation.ts'),
  ('distributed-authority-handoff-proof', 'src/authority/engine.ts'),
  ('distributed-authority-handoff-proof', 'src/authority/facts.ts'),
  ('distributed-authority-handoff-proof', 'src/authority/interaction-frontier.ts'),
  ('distributed-authority-handoff-proof', 'src/authority/judgment-frontier.ts'),
  ('distributed-authority-handoff-proof', 'src/authority/project-agent-protocol.ts'),
  ('distributed-authority-handoff-proof', 'src/authority/project-graph.ts'),
  ('distributed-authority-handoff-proof', 'src/authority/project-intent.ts'),
  ('distributed-authority-handoff-proof', 'src/authority/project-state.ts'),
  ('distributed-authority-handoff-proof', 'src/authority/realization-reuse.ts'),
  ('distributed-authority-handoff-proof', 'src/authority/realization.ts'),
  ('distributed-authority-handoff-proof', 'src/authority/replay.ts'),
  ('distributed-authority-handoff-proof', 'src/authority/store.ts'),
  ('distributed-authority-handoff-proof', 'src/authority/transaction-admission.ts'),
  ('distributed-authority-handoff-proof', 'src/providers/github/status-effect.ts'),
  ('distributed-authority-handoff-proof', 'src/source/transaction-planner.ts'),
  ('distributed-authority-handoff-proof', 'src/storage/git-kernel.ts'),
  ('distributed-authority-handoff-proof', 'src/storage/git-store.ts'),
  ('substrate-capability-admission-proof', '.github/workflows/substrate-capability-admission-treatment.yml'),
  ('substrate-capability-admission-proof', '.github/workflows/substrate-capability-admission.yml'),
  ('substrate-capability-admission-proof', 'architecture/concepts.sql'),
  ('substrate-capability-admission-proof', 'architecture/logic.sql'),
  ('substrate-capability-admission-proof', 'architecture/physics.sql'),
  ('substrate-capability-admission-proof', 'experiments/substrate-capability-admission/admission.ts'),
  ('substrate-capability-admission-proof', 'experiments/substrate-capability-admission/experiment.ts'),
  ('substrate-capability-admission-proof', 'experiments/substrate-capability-admission/fixtures.json'),
  ('substrate-capability-admission-proof', 'experiments/substrate-capability-admission/hosted-evidence.ts'),
  ('substrate-capability-admission-proof', 'scripts/plan-assurance-evidence.ts'),
  ('substrate-capability-admission-proof', 'scripts/plan-hosted-evidence.ts'),
  ('substrate-capability-admission-proof', 'src/architecture/change-planner.ts'),
  ('substrate-capability-admission-proof', 'src/architecture/sql-model.ts'),
  ('substrate-capability-admission-proof', 'src/execution/confinement/hostile_worker.rs'),
  ('substrate-capability-admission-proof', 'src/execution/confinement/main.rs'),
  ('substrate-capability-admission-proof', 'src/execution/confinement/manifest.rs'),
  ('substrate-capability-admission-proof', 'src/execution/confinement/proof.sh'),
  ('substrate-capability-admission-proof', 'src/execution/confinement/resource.rs'),
  ('substrate-capability-admission-proof', 'src/execution/confinement/resource_probe.rs'),
  ('substrate-capability-admission-proof', 'src/execution/confinement/sandbox.rs'),
  ('substrate-capability-admission-proof', 'src/execution/confinement/supervisor_proof.ts'),
  ('substrate-capability-admission-proof', 'src/execution/confinement/x32_probe.rs'),
  ('substrate-capability-admission-proof', 'src/source/transaction-planner.ts');

INSERT INTO evidence_uses_package_runtime(evidence_id) VALUES
  ('authority-flow-proof'),
  ('authority-storage-proof'),
  ('distributed-authority-chaos-proof'),
  ('distributed-authority-handoff-proof'),
  ('substrate-capability-admission-proof');

INSERT INTO evidence_uses_package_script(evidence_id, script_name) VALUES
  ('authority-flow-proof', 'typecheck'),
  ('authority-flow-proof', 'test:authority-flow-analysis'),
  ('authority-storage-proof', 'test:authority-storage-decomposition'),
  ('distributed-authority-handoff-proof', 'test:distributed-authority-handoff'),
  ('distributed-authority-chaos-proof', 'test:distributed-authority-chaos'),
  ('substrate-capability-admission-proof', 'test:substrate-capability-admission'),
  ('substrate-capability-admission-proof', 'proof:rust-exec');

INSERT INTO capability(capability_id) VALUES
  ('github-actions/permission/contents/write'),
  ('github-actions/permission/pull-requests/write'),
  ('github-actions/permission/statuses/write');

INSERT OR IGNORE INTO effect(effect_id) VALUES
  ('github-git-blob/create'),
  ('github-git-commit/create'),
  ('github-git-ref/create'),
  ('github-git-ref/delete'),
  ('github-git-ref/update'),
  ('github-git-tree/create'),
  ('github-pull-request/create'),
  ('github-source/integrate-verified-tree/v1');

INSERT INTO principal(principal_id) VALUES
  ('.github/workflows/codex-closed-loop.yml#publish'),
  ('.github/workflows/disposable-agent-proof.yml#agent-b'),
  ('.github/workflows/disposable-agent-proof.yml#effect-broker'),
  ('.github/workflows/disposable-agent-proof.yml#project-authority'),
  ('.github/workflows/distributed-authority-chaos.yml#cleanup'),
  ('.github/workflows/distributed-authority-chaos.yml#setup'),
  ('.github/workflows/distributed-authority-chaos.yml#sweep'),
  ('.github/workflows/distributed-authority-chaos.yml#verify'),
  ('.github/workflows/distributed-authority-chaos.yml#wave-one'),
  ('.github/workflows/distributed-authority-chaos.yml#wave-three'),
  ('.github/workflows/distributed-authority-chaos.yml#wave-two'),
  ('.github/workflows/distributed-authority-handoff.yml#cleanup'),
  ('.github/workflows/distributed-authority-handoff.yml#controls'),
  ('.github/workflows/distributed-authority-handoff.yml#race'),
  ('.github/workflows/distributed-authority-handoff.yml#recover'),
  ('.github/workflows/distributed-authority-handoff.yml#reserve-effect'),
  ('.github/workflows/distributed-authority-handoff.yml#setup'),
  ('.github/workflows/github-object-transport-proof.yml#publish'),
  ('.github/workflows/operator-project-advance.yml#command'),
  ('.github/workflows/operator-project-submit.yml#command'),
  ('.github/workflows/production-criticality-mutation-probe.yml#graph-obligation'),
  ('.github/workflows/production-latency.yml#github-status-latency'),
  ('.github/workflows/promote-criticality-mutation-evidence.yml#promote'),
  ('.github/workflows/substrate-capability-admission-treatment.yml#foreign-ambient-status-write'),
  ('.github/workflows/substrate-capability-admission-treatment.yml#foreign-status-write-denied'),
  ('.github/workflows/substrate-capability-admission.yml#foreign-status-write-denied');

INSERT INTO principal_defined_in_artifact(principal_id, artifact_id) VALUES
  ('.github/workflows/codex-closed-loop.yml#publish', '.github/workflows/codex-closed-loop.yml'),
  ('.github/workflows/disposable-agent-proof.yml#agent-b', '.github/workflows/disposable-agent-proof.yml'),
  ('.github/workflows/disposable-agent-proof.yml#effect-broker', '.github/workflows/disposable-agent-proof.yml'),
  ('.github/workflows/disposable-agent-proof.yml#project-authority', '.github/workflows/disposable-agent-proof.yml'),
  ('.github/workflows/distributed-authority-chaos.yml#cleanup', '.github/workflows/distributed-authority-chaos.yml'),
  ('.github/workflows/distributed-authority-chaos.yml#setup', '.github/workflows/distributed-authority-chaos.yml'),
  ('.github/workflows/distributed-authority-chaos.yml#sweep', '.github/workflows/distributed-authority-chaos.yml'),
  ('.github/workflows/distributed-authority-chaos.yml#verify', '.github/workflows/distributed-authority-chaos.yml'),
  ('.github/workflows/distributed-authority-chaos.yml#wave-one', '.github/workflows/distributed-authority-chaos.yml'),
  ('.github/workflows/distributed-authority-chaos.yml#wave-three', '.github/workflows/distributed-authority-chaos.yml'),
  ('.github/workflows/distributed-authority-chaos.yml#wave-two', '.github/workflows/distributed-authority-chaos.yml'),
  ('.github/workflows/distributed-authority-handoff.yml#cleanup', '.github/workflows/distributed-authority-handoff.yml'),
  ('.github/workflows/distributed-authority-handoff.yml#controls', '.github/workflows/distributed-authority-handoff.yml'),
  ('.github/workflows/distributed-authority-handoff.yml#race', '.github/workflows/distributed-authority-handoff.yml'),
  ('.github/workflows/distributed-authority-handoff.yml#recover', '.github/workflows/distributed-authority-handoff.yml'),
  ('.github/workflows/distributed-authority-handoff.yml#reserve-effect', '.github/workflows/distributed-authority-handoff.yml'),
  ('.github/workflows/distributed-authority-handoff.yml#setup', '.github/workflows/distributed-authority-handoff.yml'),
  ('.github/workflows/github-object-transport-proof.yml#publish', '.github/workflows/github-object-transport-proof.yml'),
  ('.github/workflows/operator-project-advance.yml#command', '.github/workflows/operator-project-advance.yml'),
  ('.github/workflows/operator-project-submit.yml#command', '.github/workflows/operator-project-submit.yml'),
  ('.github/workflows/production-criticality-mutation-probe.yml#graph-obligation', '.github/workflows/production-criticality-mutation-probe.yml'),
  ('.github/workflows/production-latency.yml#github-status-latency', '.github/workflows/production-latency.yml'),
  ('.github/workflows/promote-criticality-mutation-evidence.yml#promote', '.github/workflows/promote-criticality-mutation-evidence.yml'),
  ('.github/workflows/substrate-capability-admission-treatment.yml#foreign-ambient-status-write', '.github/workflows/substrate-capability-admission-treatment.yml'),
  ('.github/workflows/substrate-capability-admission-treatment.yml#foreign-status-write-denied', '.github/workflows/substrate-capability-admission-treatment.yml'),
  ('.github/workflows/substrate-capability-admission.yml#foreign-status-write-denied', '.github/workflows/substrate-capability-admission.yml');

INSERT INTO principal_has_capability(principal_id, capability_id) VALUES
  ('.github/workflows/codex-closed-loop.yml#publish', 'github-actions/permission/contents/write'),
  ('.github/workflows/codex-closed-loop.yml#publish', 'github-actions/permission/pull-requests/write'),
  ('.github/workflows/disposable-agent-proof.yml#agent-b', 'github-actions/permission/contents/write'),
  ('.github/workflows/disposable-agent-proof.yml#effect-broker', 'github-actions/permission/contents/write'),
  ('.github/workflows/disposable-agent-proof.yml#effect-broker', 'github-actions/permission/statuses/write'),
  ('.github/workflows/disposable-agent-proof.yml#project-authority', 'github-actions/permission/contents/write'),
  ('.github/workflows/distributed-authority-chaos.yml#cleanup', 'github-actions/permission/contents/write'),
  ('.github/workflows/distributed-authority-chaos.yml#setup', 'github-actions/permission/contents/write'),
  ('.github/workflows/distributed-authority-chaos.yml#sweep', 'github-actions/permission/contents/write'),
  ('.github/workflows/distributed-authority-chaos.yml#verify', 'github-actions/permission/contents/write'),
  ('.github/workflows/distributed-authority-chaos.yml#wave-one', 'github-actions/permission/contents/write'),
  ('.github/workflows/distributed-authority-chaos.yml#wave-three', 'github-actions/permission/contents/write'),
  ('.github/workflows/distributed-authority-chaos.yml#wave-two', 'github-actions/permission/contents/write'),
  ('.github/workflows/distributed-authority-handoff.yml#cleanup', 'github-actions/permission/contents/write'),
  ('.github/workflows/distributed-authority-handoff.yml#cleanup', 'github-actions/permission/statuses/write'),
  ('.github/workflows/distributed-authority-handoff.yml#controls', 'github-actions/permission/contents/write'),
  ('.github/workflows/distributed-authority-handoff.yml#controls', 'github-actions/permission/statuses/write'),
  ('.github/workflows/distributed-authority-handoff.yml#race', 'github-actions/permission/contents/write'),
  ('.github/workflows/distributed-authority-handoff.yml#race', 'github-actions/permission/statuses/write'),
  ('.github/workflows/distributed-authority-handoff.yml#recover', 'github-actions/permission/contents/write'),
  ('.github/workflows/distributed-authority-handoff.yml#recover', 'github-actions/permission/statuses/write'),
  ('.github/workflows/distributed-authority-handoff.yml#reserve-effect', 'github-actions/permission/contents/write'),
  ('.github/workflows/distributed-authority-handoff.yml#reserve-effect', 'github-actions/permission/statuses/write'),
  ('.github/workflows/distributed-authority-handoff.yml#setup', 'github-actions/permission/contents/write'),
  ('.github/workflows/distributed-authority-handoff.yml#setup', 'github-actions/permission/statuses/write'),
  ('.github/workflows/github-object-transport-proof.yml#publish', 'github-actions/permission/contents/write'),
  ('.github/workflows/operator-project-advance.yml#command', 'github-actions/permission/contents/write'),
  ('.github/workflows/operator-project-submit.yml#command', 'github-actions/permission/contents/write'),
  ('.github/workflows/production-criticality-mutation-probe.yml#graph-obligation', 'github-actions/permission/contents/write'),
  ('.github/workflows/production-latency.yml#github-status-latency', 'github-actions/permission/statuses/write'),
  ('.github/workflows/promote-criticality-mutation-evidence.yml#promote', 'github-actions/permission/contents/write'),
  ('.github/workflows/substrate-capability-admission-treatment.yml#foreign-ambient-status-write', 'github-actions/permission/statuses/write');

INSERT INTO principal_invokes_effect(principal_id, effect_id) VALUES
  ('.github/workflows/codex-closed-loop.yml#publish', 'github-git-ref/update'),
  ('.github/workflows/codex-closed-loop.yml#publish', 'github-pull-request/create'),
  ('.github/workflows/distributed-authority-chaos.yml#cleanup', 'github-git-ref/delete'),
  ('.github/workflows/distributed-authority-handoff.yml#cleanup', 'github-git-ref/delete'),
  ('.github/workflows/github-object-transport-proof.yml#publish', 'github-git-blob/create'),
  ('.github/workflows/github-object-transport-proof.yml#publish', 'github-git-commit/create'),
  ('.github/workflows/github-object-transport-proof.yml#publish', 'github-git-ref/create'),
  ('.github/workflows/github-object-transport-proof.yml#publish', 'github-git-tree/create'),
  ('.github/workflows/promote-criticality-mutation-evidence.yml#promote', 'github-git-ref/update'),
  ('.github/workflows/substrate-capability-admission-treatment.yml#foreign-ambient-status-write', 'github-commit-status/create'),
  ('.github/workflows/substrate-capability-admission-treatment.yml#foreign-status-write-denied', 'github-commit-status/create'),
  ('.github/workflows/substrate-capability-admission.yml#foreign-status-write-denied', 'github-commit-status/create');

INSERT INTO principal_reaches_effect(principal_id, effect_id) VALUES
  ('.github/workflows/operator-project-submit.yml#command', 'github-source/integrate-verified-tree/v1');

INSERT INTO principal_holds_authority(principal_id, authority_id) VALUES
  ('.github/workflows/disposable-agent-proof.yml#agent-b', 'execution-authority'),
  ('.github/workflows/disposable-agent-proof.yml#effect-broker', 'effect-authority'),
  ('.github/workflows/disposable-agent-proof.yml#project-authority', 'project-authority');
