CREATE TABLE IF NOT EXISTS work_leases (
  lease_id uuid PRIMARY KEY,
  work_ref text NOT NULL,
  gate text NOT NULL,
  run_id text NOT NULL,
  lease_token text NOT NULL,
  token_hash text NOT NULL UNIQUE CHECK (token_hash ~ '^[0-9a-f]{64}$'),
  claim_idempotency_key text NOT NULL UNIQUE,
  claim_request_hash text NOT NULL CHECK (claim_request_hash ~ '^[0-9a-f]{64}$'),
  status text NOT NULL CHECK (status IN ('claiming','active','settling','settled','expired','invalidated','rejected')),
  created_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  previous_state text NOT NULL,
  previous_state_id text NOT NULL,
  previous_lane text NOT NULL,
  previous_lane_id text NOT NULL,
  claim_revision text NOT NULL,
  active_revision text,
  claim_receipt jsonb,
  settle_idempotency_key text UNIQUE,
  settle_request_hash text CHECK (settle_request_hash IS NULL OR settle_request_hash ~ '^[0-9a-f]{64}$'),
  settle_plan jsonb,
  settle_receipt jsonb,
  settled_at timestamptz,
  reconciliation jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
)