import { createGithubRelease, normalizeGithubReleaseRequest } from './github-release.js';
const REPO='laurajoyhutchins/example', SHA='1111111111111111111111111111111111111111', TAG='v1.2.3', BASE='/repos/laurajoyhutchins/example';
function ok(c,m){if(!c)throw new Error(m||'assertion failed');} async function t(name,fn){try{await fn();return{name,ok:true};}catch(e){return{name,ok:false,error:String(e?.message||e)};}} function rsp(status,body){return{status,body,headers:{}};}
function rel(o={}){return{id:77,tag_name:TAG,name:'Release 1.2.3',body:'Notes',draft:false,prerelease:false,html_url:'https://github.com/x',created_at:'2026-08-26T22:00:00Z',published_at:'2026-08-26T22:00:01Z',...o};} function tag(sha=SHA){return{ref:`refs/tags/${TAG}`,node_id:'REF_node',object:{type:'commit',sha}};}
function q(steps){const calls=[];return{calls,async call(name,r){ok(name==='github','api');const s=steps.shift();ok(s,`unexpected ${r.method||'GET'} ${r.path}`);if(s.method)ok((r.method||'GET')===s.method,'method');if(s.path)ok(r.path===s.path,`expected ${s.path} got ${r.path}`);s.inspect?.(r);calls.push(r);if(s.result instanceof Error)throw s.result;return s.result;}};}
const req=(o={})=>({repo:REPO,target_sha:SHA,tag_name:TAG,name:'Release 1.2.3',body:'Notes',draft:false,prerelease:false,expected_state:{tag:'absent',release:'absent'},idempotency_key:'release-example-v1',...o});
const observe=(tg=null,re=null)=>[{method:'GET',path:BASE,result:rsp(200,{id:10,full_name:REPO})},{method:'GET',path:`${BASE}/commits/${SHA}`,result:rsp(200,{sha:SHA})},{method:'GET',path:`${BASE}/git/ref/tags/${TAG}`,result:tg?rsp(200,tg):rsp(404,{})},{method:'GET',path:`${BASE}/releases/tags/${TAG}`,result:re?rsp(200,re):rsp(404,{})}];
export async function runGithubReleaseTests(){const r=[];
r.push(await t('normalizes exact SHA and expected-state semantics',async()=>{ok(normalizeGithubReleaseRequest(req()).target_sha===SHA);let e;try{normalizeGithubReleaseRequest(req({target_sha:'main'}));}catch(x){e=x;}ok(e?.code==='INVALID_REQUEST','accepted commit-ish');}));
r.push(await t('creates lightweight tag then release and verifies both',async()=>{const c=q([...observe(),{method:'POST',path:`${BASE}/git/refs`,inspect:x=>ok(x.body.ref===`refs/tags/${TAG}`&&x.body.sha===SHA),result:rsp(201,tag())},{method:'POST',path:`${BASE}/releases`,inspect:x=>ok(x.body.tag_name===TAG&&!('target_commitish'in x.body),'release retarget field'),result:rsp(201,rel())},...observe(tag(),rel())]);const x=await createGithubRelease(req(),{apiClient:c});ok(x.ok&&x.outcome==='created'&&x.verified&&x.verified_commit_sha===SHA,'not verified');}));
r.push(await t('exact idempotent existing state is already satisfied',async()=>{const c=q(observe(tag(),rel()));const x=await createGithubRelease(req({expected_state:{tag:'present_same_commit',release:'present_matching'}}),{apiClient:c});ok(x.ok&&x.outcome==='already_satisfied'&&x.created===false); }));
r.push(await t('same tag at different commit conflicts',async()=>{const c=q(observe(tag('2222222222222222222222222222222222222222'),null));const x=await createGithubRelease(req({expected_state:{tag:'present_same_commit',release:'absent'}}),{apiClient:c});ok(!x.ok&&x.error==='GITHUB_RELEASE_TAG_CONFLICT'&&!x.may_have_mutated);}));
r.push(await t('matching release is accepted but differing release conflicts',async()=>{let c=q(observe(tag(),rel()));let x=await createGithubRelease(req({expected_state:{tag:'present_same_commit',release:'present_matching'}}),{apiClient:c});ok(x.ok);c=q(observe(tag(),rel({body:'other'})));x=await createGithubRelease(req({expected_state:{tag:'present_same_commit',release:'present_matching'}}),{apiClient:c});ok(!x.ok&&x.error==='GITHUB_RELEASE_STATE_CONFLICT');}));
r.push(await t('missing target commit fails before mutation',async()=>{const c=q([{method:'GET',path:BASE,result:rsp(200,{id:10})},{method:'GET',path:`${BASE}/commits/${SHA}`,result:rsp(404,{})}]);const x=await createGithubRelease(req(),{apiClient:c});ok(!x.ok&&x.error==='GITHUB_RELEASE_TARGET_NOT_FOUND'&&c.calls.every(a=>(a.method||'GET')==='GET'));}));
r.push(await t('expected-state mismatch fails closed',async()=>{const c=q(observe(tag(),null));const x=await createGithubRelease(req(),{apiClient:c});ok(!x.ok&&x.error==='GITHUB_RELEASE_STATE_CHANGED'&&!x.may_have_mutated);}));
r.push(await t('verification failure remains indeterminate',async()=>{const c=q([...observe(),{method:'POST',path:`${BASE}/git/refs`,result:rsp(201,tag())},{method:'POST',path:`${BASE}/releases`,result:rsp(201,rel())},...observe(tag('3333333333333333333333333333333333333333'),rel())]);const x=await createGithubRelease(req(),{apiClient:c});ok(!x.ok&&x.error==='GITHUB_RELEASE_VERIFICATION_FAILED'&&x.may_have_mutated);}));
r.push(await t('tag-created release failure recovers safely on retry',async()=>{const store={row:null,async claim(n,d){if(!this.row){this.row={request_sha256:d,state:'processing',tag_created:false};return{kind:'claimed',row:this.row,attempt_token:'test-attempt'};}return this.row.request_sha256===d?{kind:'claimed',row:this.row,attempt_token:'test-attempt',resumed:true}:{kind:'conflict',row:this.row};},async markTag(){this.row.tag_created=true;},async succeed(n,a,x){this.row.state='succeeded';this.row.receipt=x;},async markPartial(n,a,d){this.row.state='partial';this.row.release_may_exist=Boolean(d?.release_may_exist);}};let c=q([...observe(),{method:'POST',path:`${BASE}/git/refs`,result:rsp(201,tag())},{method:'POST',path:`${BASE}/releases`,result:new Error('boom')}]);let x=await createGithubRelease(req(),{apiClient:c,receiptStore:store});ok(!x.ok&&store.row.tag_created,'partial not durable');c=q([...observe(tag(),null),{method:'POST',path:`${BASE}/releases`,result:rsp(201,rel())},...observe(tag(),rel())]);x=await createGithubRelease(req(),{apiClient:c,receiptStore:store});ok(x.ok&&x.verified,'retry failed');}));
r.push(await t('exact duplicate request with same idempotency identity converges',async()=>{const store={async claim(){return{kind:'existing',row:{request_sha256:'same',state:'succeeded',tag_created:true}};},async succeed(){}};const c=q(observe(tag(),rel()));const x=await createGithubRelease(req(),{apiClient:c,receiptStore:store});ok(x.ok&&x.outcome==='already_satisfied'&&x.idempotent_replay===true); }));
r.push(await t('idempotency key cannot be reused for different semantics',async()=>{const store={async claim(){return{kind:'conflict',row:{request_sha256:'different'}};}};const x=await createGithubRelease(req(),{apiClient:q([]),receiptStore:store});ok(!x.ok&&x.error==='IDEMPOTENCY_CONFLICT');}));
r.push(await t('draft and prerelease flags are material',async()=>{const x=normalizeGithubReleaseRequest(req({draft:true,prerelease:true}));ok(x.draft&&x.prerelease);}));
r.push(await t('same-commit tag without release continues safely',async()=>{const c=q([...observe(tag(),null),{method:'POST',path:BASE+'/releases',result:rsp(201,rel())},...observe(tag(),rel())]);const x=await createGithubRelease(req({expected_state:{tag:'present_same_commit',release:'absent'}}),{apiClient:c});ok(x.ok&&x.outcome==='created'&&x.verified);}));
r.push(await t('semantic request hash excludes idempotency identity',async()=>{let c=q(observe(tag(),rel()));const a=await createGithubRelease(req({idempotency_key:'identity-a',expected_state:{tag:'present_same_commit',release:'present_matching'}}),{apiClient:c});c=q(observe(tag(),rel()));const b=await createGithubRelease(req({idempotency_key:'identity-b',expected_state:{tag:'present_same_commit',release:'present_matching'}}),{apiClient:c});ok(a.request_sha256===b.request_sha256,'idempotency key polluted semantic request hash');}));
r.push(await t('ambiguous release response is reported as potentially mutated when tag pre-existed',async()=>{const c=q([...observe(tag(),null),{method:'POST',path:BASE+'/releases',result:rsp(500,{message:'temporary failure'})}]);const x=await createGithubRelease(req({expected_state:{tag:'present_same_commit',release:'absent'}}),{apiClient:c});ok(!x.ok&&x.error==='GITHUB_RELEASE_INDETERMINATE'&&x.may_have_mutated===true,'ambiguous release POST was reported as non-mutating');}));
return{ok:r.every(x=>x.ok),passed:r.filter(x=>x.ok).length,failed:r.filter(x=>!x.ok).length,tests:r};}
