import { githubAppPermissionProfile } from 'lib/github-app-auth.js';
import { safeRequestProjection, safeResultProjection } from 'lib/orchestration-journal.js';
import { validateSemanticWorkerCommand } from 'lib/worker-transport.js';
import { createGithubRelease, normalizeGithubReleaseRequest } from 'lib/github-release.js';
const REPO='laurajoyhutchins/example', SHA='1111111111111111111111111111111111111111', TAG='v1.2.3', BASE='/repos/laurajoyhutchins/example';
function ok(c,m){if(!c)throw new Error(m||'assertion failed');} async function t(name,fn){try{await fn();return{name,ok:true};}catch(e){return{name,ok:false,error:String(e?.message||e)};}} function rsp(status,body){return{status,body,headers:{}};}
function rel(o={}){return{id:77,tag_name:TAG,name:'Release 1.2.3',body:'Notes',draft:false,prerelease:false,html_url:'https://github.com/x',created_at:'2026-08-26T22:00:00Z',published_at:'2026-08-26T22:00:01Z',...o};} function tag(sha=SHA){return{ref:`refs/tags/${TAG}`,node_id:'REF_node',object:{type:'commit',sha}};}
function q(steps){const calls=[];return{calls,async call(name,r){ok(name==='github','api');const s=steps.shift();ok(s,`unexpected ${r.method||'GET'} ${r.path}`);if(s.method)ok((r.method||'GET')===s.method,'method');if(s.path)ok(r.path===s.path,`expected ${s.path} got ${r.path}`);s.inspect?.(r);calls.push(r);if(s.result instanceof Error)throw s.result;return s.result;}};}
const req=(o={})=>({repo:REPO,target_sha:SHA,tag_name:TAG,name:'Release 1.2.3',body:'Notes',draft:false,prerelease:false,expected_state:{tag:'absent',release:'absent'},idempotency_key:'release-example-v1',...o});
const observe=(tg=null,re=null)=>[{method:'GET',path:BASE,result:rsp(200,{id:10,full_name:REPO})},{method:'GET',path:`${BASE}/commits/${SHA}`,result:rsp(200,{sha:SHA})},{method:'GET',path:`${BASE}/git/ref/tags/${TAG}`,result:tg?rsp(200,tg):rsp(404,{})},{method:'GET',path:`${BASE}/releases/tags/${TAG}`,result:re?rsp(200,re):rsp(404,{})}];
export async function runGithubReleaseTests(){const r=[];
r.push(await t('normalizes exact SHA and expected-state semantics',async()=>{ok(normalizeGithubReleaseRequest(req()).target_sha===SHA);let e;try{normalizeGithubReleaseRequest(req({target_sha:'main'}));}catch(x){e=x;}ok(e?.code==='INVALID_REQUEST','accepted commit-ish');}));
r.push(await t('uses only contents write permission',async()=>ok(JSON.stringify(githubAppPermissionProfile('release'))===JSON.stringify({contents:'write'}),'permission broadened')));
r.push(await t('creates lightweight tag then release and verifies both',async()=>{const c=q([...observe(),{method:'POST',path:`${BASE}/git/refs`,inspect:x=>ok(x.body.ref===`refs/tags/${TAG}`&&x.body.sha===SHA),result:rsp(201,tag())},{method:'POST',path:`${BASE}/releases`,inspect:x=>ok(x.body.tag_name===TAG&&!('target_commitish'in x.body),'release retarget field'),result:rsp(201,rel())},{method:'GET',path:`${BASE}/git/ref/tags/${TAG}`,result:rsp(200,tag())},{method:'GET',path:`${BASE}/releases/tags/${TAG}`,result:rsp(200,rel())}]);const x=await createGithubRelease(req(),{apiClient:c});ok(x.ok&&x.outcome==='created'&&x.verified&&x.verified_commit_sha===SHA,'not verified');}));
r.push(await t('exact idempotent existing state is already satisfied',async()=>{const c=q(observe(tag(),rel()));const x=await createGithubRelease(req({expected_state:{tag:'present_same_commit',release:'present_matching'}}),{apiClient:c});ok(x.ok&&x.outcome==='already_satisfied'&&x.created===false); }));
r.push(await t('same tag at different commit conflicts',async()=>{const c=q(observe(tag('2222222222222222222222222222222222222222'),null));const x=await createGithubRelease(req({expected_state:{tag:'present_same_commit',release:'absent'}}),{apiClient:c});ok(!x.ok&&x.error==='GITHUB_RELEASE_TAG_CONFLICT'&&!x.may_have_mutated);}));
r.push(await t('matching release is accepted but differing release conflicts',async()=>{let c=q(observe(tag(),rel()));let x=await createGithubRelease(req({expected_state:{tag:'present_same_commit',release:'present_matching'}}),{apiClient:c});ok(x.ok);c=q(observe(tag(),rel({body:'other'})));x=await createGithubRelease(req({expected_state:{tag:'present_same_commit',release:'present_matching'}}),{apiClient:c});ok(!x.ok&&x.error==='GITHUB_RELEASE_STATE_CONFLICT');}));
r.push(await t('missing target commit fails before mutation',async()=>{const c=q([{method:'GET',path:BASE,result:rsp(200,{id:10})},{method:'GET',path:`${BASE}/commits/${SHA}`,result:rsp(404,{})}]);const x=await createGithubRelease(req(),{apiClient:c});ok(!x.ok&&x.error==='GITHUB_RELEASE_TARGET_NOT_FOUND'&&c.calls.every(a=>(a.method||'GET')==='GET'));}));
r.push(await t('expected-state mismatch fails closed',async()=>{const c=q(observe(tag(),null));const x=await createGithubRelease(req(),{apiClient:c});ok(!x.ok&&x.error==='GITHUB_RELEASE_STATE_CHANGED'&&!x.may_have_mutated);}));
r.push(await t('verification failure remains indeterminate',async()=>{const c=q([...observe(),{method:'POST',path:`${BASE}/git/refs`,result:rsp(201,tag())},{method:'POST',path:`${BASE}/releases`,result:rsp(201,rel())},{method:'GET',path:`${BASE}/git/ref/tags/${TAG}`,result:rsp(200,tag('3333333333333333333333333333333333333333'))},{method:'GET',path:`${BASE}/releases/tags/${TAG}`,result:rsp(200,rel())}]);const x=await createGithubRelease(req(),{apiClient:c});ok(!x.ok&&x.error==='GITHUB_RELEASE_VERIFICATION_FAILED'&&x.may_have_mutated);}));
r.push(await t('tag-created release failure recovers safely on retry',async()=>{const store={row:null,async claim(n,d){if(!this.row){this.row={request_sha256:d,state:'processing',tag_created:false};return{kind:'claimed',row:this.row};}return this.row.request_sha256===d?{kind:'claimed',row:this.row}:{kind:'conflict',row:this.row};},async markTag(){this.row.tag_created=true;},async succeed(n,x){this.row.state='succeeded';this.row.receipt=x;},async markPartial(){this.row.tag_created=true;}};let c=q([...observe(),{method:'POST',path:`${BASE}/git/refs`,result:rsp(201,tag())},{method:'POST',path:`${BASE}/releases`,result:new Error('boom')}]);let x=await createGithubRelease(req(),{apiClient:c,receiptStore:store});ok(!x.ok&&store.row.tag_created,'partial not durable');c=q([...observe(tag(),null),{method:'POST',path:`${BASE}/releases`,result:rsp(201,rel())},{method:'GET',path:`${BASE}/git/ref/tags/${TAG}`,result:rsp(200,tag())},{method:'GET',path:`${BASE}/releases/tags/${TAG}`,result:rsp(200,rel())}]);x=await createGithubRelease(req(),{apiClient:c,receiptStore:store});ok(x.ok&&x.verified,'retry failed');}));
r.push(await t('idempotency key cannot be reused for different semantics',async()=>{const store={async claim(){return{kind:'conflict',row:{request_sha256:'different'}};}};const x=await createGithubRelease(req(),{apiClient:q([]),receiptStore:store});ok(!x.ok&&x.error==='IDEMPOTENCY_CONFLICT');}));
r.push(await t('draft and prerelease flags are material',async()=>{const x=normalizeGithubReleaseRequest(req({draft:true,prerelease:true}));ok(x.draft&&x.prerelease);}));
r.push(await t('semantic worker route accepts documented shape and rejects REST bookkeeping',async()=>{const x=validateSemanticWorkerCommand('github.release.create',{...req(),run_id:'r'});ok(x.tag_name===TAG);let e;try{validateSemanticWorkerCommand('github.release.create',{...req(),run_id:'r',target_commitish:'main'});}catch(z){e=z;}ok(e?.code==='REQUEST_INVALID','REST field accepted');}));
r.push(await t('journal preserves stable evidence without release body',async()=>{const a=safeRequestProjection('github.release.create',{...req(),body:'secret-ish notes'});ok(a.tag_name===TAG&&!JSON.stringify(a).includes('secret-ish notes'));const b=safeResultProjection('github.release.create',{repo:REPO,tag_name:TAG,requested_commit_sha:SHA,verified_commit_sha:SHA,release_id:77,outcome:'created',verified:true});ok(b.release_id===77&&b.verified_commit_sha===SHA);}));
return{ok:r.every(x=>x.ok),passed:r.filter(x=>x.ok).length,failed:r.filter(x=>!x.ok).length,tests:r};}