import test from 'node:test';
import assert from 'node:assert/strict';
import { createProjectArtifactBinding, classifyBoundArtifactSatisfaction } from './project-artifact-binding.js';
const REVISION='0eab1f9a7c467194d3b5e0e61c46650b1d19b8a3';
const bindingInput=()=>({project_ref:'github:laurajoyhutchins/overcenter',transition_id:'add-project-artifact-binding',authority_revision:REVISION,relationship:'full-coverage-equivalence',provider:{repository:'laurajoyhutchins/overcenter',kind:'issue',id:42,state:'open'},satisfaction:{kind:'provider-closed',requires_exact_binding:true}});
const cases=[
 ['explicit binding preserves exact semantic and provider identity',()=>{const binding=createProjectArtifactBinding(bindingInput());assert.equal(binding.schema,'project-artifact-binding-v1');assert.equal(binding.provenance,'explicit-judgment');assert.deepEqual(binding.subject,{project_ref:'github:laurajoyhutchins/overcenter',transition_id:'add-project-artifact-binding',authority_revision:REVISION});assert.deepEqual(binding.provider,{repository:'laurajoyhutchins/overcenter',kind:'issue',id:42,state:'open'});assert.equal(binding.relationship,'full-coverage-equivalence');assert.deepEqual(binding.satisfaction,{kind:'provider-closed',requires_exact_binding:true});}],
 ['only an exactly bound artifact can mechanically satisfy the obligation',()=>{const binding=createProjectArtifactBinding(bindingInput());assert.deepEqual(classifyBoundArtifactSatisfaction(binding,{repository:'laurajoyhutchins/overcenter',kind:'issue',id:42,state:'closed'}),{classification:'satisfied',evidence:{provider_state:'closed',provider_id:42}});assert.deepEqual(classifyBoundArtifactSatisfaction(binding,{repository:'laurajoyhutchins/overcenter',kind:'issue',id:43,state:'closed'}),{classification:'ambiguous',evidence:{reason:'artifact-not-explicitly-bound'}});}],
 ['binding fails closed on repository or authority ambiguity',()=>{assert.throws(()=>createProjectArtifactBinding({...bindingInput(),authority_revision:'not-a-revision'}),/authority_revision/);assert.throws(()=>createProjectArtifactBinding({...bindingInput(),provider:{...bindingInput().provider,repository:'someone/else'}}),/repository/);}],
];
for(const [name,run] of cases)test(name,run);
export async function runProjectArtifactBindingTests(){for(const [,run] of cases)run();return {ok:true,passed:cases.length,failed:0,total:cases.length};}