import { createExecutionAuthorityService } from './execution-authority-core.js';
import { createProjectTransitionLeasePostgresStore, prepareProjectTransitionLeasePersistence, restoreProjectTransitionLease } from './project-transition-lease-store.js';
import { createProjectTransitionLeaseService } from './project-transition-leases.js';
import * as projectTransitionLeases from './project-transition-leases.js';
import { projectTransitionDefinitionFingerprint } from './project-transition-observations.js';
import { PRODUCTIVE_STAGES } from './work-lifecycle.js';

function assert(value, message) { if (!value) throw new Error(message); }
function expectCode(fn, code) { return Promise.resolve().then(fn).then(()=>{ throw new Error(`expected ${code}`); }, error=>{ if (error?.code !== code) throw error; return error; }); }
function responsibilitiesFor(target) { const index=PRODUCTIVE_STAGES.indexOf(target); return Object.fromEntries(PRODUCTIVE_STAGES.map((stage,stageIndex)=>[stage,{applicable:true,satisfied:stageIndex<index}])); }

function fixture(){
  let now=Date.parse('2026-08-27T13:00:00Z'); const runs=new Map([['run-1',{run_id:'run-1',status:'active',deadline_at:'2026-08-27T14:00:00Z'}],['run-2',{run_id:'run-2',status:'active',deadline_at:'2026-08-27T14:00:00Z'}]]); const leases=new Map(); const slots=new Map();
  const store={async getRun(id){return runs.get(id)||null;},async getLease(id){return leases.get(id)||null;},async getLeaseByAcquireIdempotency(key){return [...leases.values()].find(row=>row.acquire_idempotency_key===key)||null;},async getSlot(key){return slots.get(key)||null;},async insertLease(row){leases.set(row.lease_id,{...row});return leases.get(row.lease_id);},async insertSlot(row){if(slots.has(row.slot_key)){const e=new Error('occupied');e.code='UNIQUE_VIOLATION';throw e;}slots.set(row.slot_key,{...row});return slots.get(row.slot_key);},async updateLease(id,patch){const row={...leases.get(id),...patch};leases.set(id,row);return row;},async deleteSlot(key,id){if(slots.get(key)?.lease_id===id)slots.delete(key);}};
  const graph={schema:'project-graph-authority-v1',project_ref:'github:laurajoyhutchins/overcenter',authority:{definition:{kind:'github',repository:'laurajoyhutchins/overcenter',revision:'1'.repeat(40),derivation:'overcenter-project-graph-v1'},observations:[]},nodes:[{id:'transition-a',priority:1,requires:[],lifecycle:{current_stage:'ENABLE',responsibilities:responsibilitiesFor('ENABLE')},executor:{kind:'agent',role:'engineering',skill:'implementation'},phase_bindings:{}}],horizons:[]}; let currentGraph=graph;
  const service=createProjectTransitionLeaseService({store,readProjectGraph:async()=>currentGraph,now:()=>new Date(now).toISOString(),uuid:()=>`00000000-0000-4000-8000-${String(leases.size+1).padStart(12,'0')}`}); return{service,store,setGraph(value){currentGraph=value;},advance(ms){now+=ms;},graph};
}

function executionAuthorityFixture(){
  const leaseRef='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',runId='run-project-transition',repository='laurajoyhutchins/overcenter'; const lease={lease_id:leaseRef,work_ref:'project_transition:overcenter:transition-a',gate:'project_transition',run_id:runId,status:'active',expires_at:'2026-08-27T13:30:00Z',hard_expires_at:'2026-08-27T14:00:00Z',claim_receipt:{subject:'project_transition',project_transition:{project_ref:'github:laurajoyhutchins/overcenter',transition_id:'transition-a',repository,authority_revision:'1'.repeat(40),graph_fingerprint:'f'.repeat(64),transition_definition_fingerprint:'d'.repeat(64)}}}; let projectTransitionReads=0;
  const store={async getLeaseById(id){return id===leaseRef?lease:null;},async getLeaseByTokenHash(){return null;}};
  const projectTransitions={async require(input){projectTransitionReads+=1;assert(input.lease_ref===leaseRef,'project transition lease reference changed');assert(input.repository===repository,'repository scope was not forwarded');return{ok:true,lease_ref:leaseRef,subject:'project_transition',run_id:runId,project_ref:'github:laurajoyhutchins/overcenter',transition_id:'transition-a',repository,authority:{kind:'github',repository,revision:'1'.repeat(40),derivation:'overcenter-project-graph-v1'},graph_fingerprint:'f'.repeat(64),transition_definition_fingerprint:'d'.repeat(64)};}};
  const service=createExecutionAuthorityService({store,projectTransitions,now:()=> '2026-08-27T13:00:00Z'}); return{service,leaseRef,repository,counts:()=>({projectTransitionReads})};
}

export async function runProjectTransitionLeaseTests(){
  const tests=[]; async function test(name,fn){try{await fn();tests.push({name,ok:true});}catch(error){tests.push({name,ok:false,error:String(error?.message||error)});}}
  await test('acquires one exact READY project transition with non-secret lease reference',async()=>{const f=fixture();const r=await f.service.acquire({run_id:'run-1',project_ref:'github:laurajoyhutchins/overcenter',transition_id:'transition-a',lease_seconds:600,idempotency_key:'a'});assert(r.ok&&r.lease_ref&&!('lease_token'in r),'lease reference contract failed');assert(r.authority.repository==='laurajoyhutchins/overcenter'&&r.authority.revision==='1'.repeat(40),'authority coordinate missing');assert(/^[0-9a-f]{64}$/.test(r.transition_definition_fingerprint),'transition-definition fingerprint missing');});
  await test('exact acquire replay returns the same authority while idempotency conflicts fail closed',async()=>{const f=fixture();const request={run_id:'run-1',project_ref:'github:laurajoyhutchins/overcenter',transition_id:'transition-a',lease_seconds:600,idempotency_key:'replay'};const a=await f.service.acquire(request);const b=await f.service.acquire(request);assert(a.lease_ref===b.lease_ref&&b.idempotent_replay===true,'exact acquire replay created new authority');await expectCode(()=>f.service.acquire({...request,lease_seconds:900}),'PROJECT_TRANSITION_IDEMPOTENCY_CONFLICT');});
  await test('competing acquisition of same transition revision is rejected',async()=>{const f=fixture();await f.service.acquire({run_id:'run-1',project_ref:'github:laurajoyhutchins/overcenter',transition_id:'transition-a',lease_seconds:600,idempotency_key:'a'});await expectCode(()=>f.service.acquire({run_id:'run-2',project_ref:'github:laurajoyhutchins/overcenter',transition_id:'transition-a',lease_seconds:600,idempotency_key:'b'}),'PROJECT_TRANSITION_ALREADY_LEASED');});
  await test('non-READY transition is rejected before lease creation',async()=>{const f=fixture();f.setGraph({...f.graph,nodes:[{...f.graph.nodes[0],lifecycle:{current_stage:'EXECUTE',condition:'HOLD',responsibilities:responsibilitiesFor('COMMIT')}}]});await expectCode(()=>f.service.acquire({run_id:'run-1',project_ref:'github:laurajoyhutchins/overcenter',transition_id:'transition-a',lease_seconds:600,idempotency_key:'a'}),'PROJECT_TRANSITION_NOT_READY');});
  await test('settlement is deterministic and stale authority cannot be reused',async()=>{const f=fixture();const a=await f.service.acquire({run_id:'run-1',project_ref:'github:laurajoyhutchins/overcenter',transition_id:'transition-a',lease_seconds:600,idempotency_key:'a'});const s=await f.service.settle({lease_ref:a.lease_ref,run_id:'run-1',disposition:'completed',idempotency_key:'s'});assert(s.status==='settled'&&s.disposition==='completed','settlement failed');await expectCode(()=>f.service.settle({lease_ref:a.lease_ref,run_id:'run-1',disposition:'blocked',idempotency_key:'other'}),'PROJECT_TRANSITION_LEASE_ALREADY_SETTLED');});
  await test('cross-revision settlement returns compact graph revision evidence',async()=>{const f=fixture();const a=await f.service.acquire({run_id:'run-1',project_ref:'github:laurajoyhutchins/overcenter',transition_id:'transition-a',lease_seconds:600,idempotency_key:'settlement-revision-evidence'});f.store.getActiveLeasesForTransition=async()=>[await f.store.getLease(a.lease_ref)];f.setGraph({...f.graph,authority:{...f.graph.authority,definition:{...f.graph.authority.definition,revision:'2'.repeat(40)}}});const s=await f.service.settle({lease_ref:a.lease_ref,run_id:'run-1',disposition:'requeue',idempotency_key:'settlement-revision-evidence'});assert(s.graph_revision_change?.schema==='project-graph-revision-change-v1','settlement discarded graph revision evidence');assert(s.graph_revision_change?.previous_authority?.revision==='1'.repeat(40),'settlement lost previous graph authority');assert(s.graph_revision_change?.current_authority?.revision==='2'.repeat(40),'settlement lost current graph authority');});
  await test('dependency-only graph revision invalidates stale transition authority',async()=>{const f=fixture();const a=await f.service.acquire({run_id:'run-1',project_ref:'github:laurajoyhutchins/overcenter',transition_id:'transition-a',lease_seconds:600,idempotency_key:'dependency-change'});f.store.getActiveLeasesForTransition=async()=>[await f.store.getLease(a.lease_ref)];f.setGraph({...f.graph,authority:{...f.graph.authority,definition:{...f.graph.authority.definition,revision:'2'.repeat(40)}},nodes:[{...f.graph.nodes[0],requires:['new-prerequisite']},{id:'new-prerequisite',priority:2,requires:[],lifecycle:{current_stage:'CONFIRM',condition:'NOMINAL',responsibilities:Object.fromEntries(PRODUCTIVE_STAGES.map(stage=>[stage,{applicable:true,satisfied:true}]))},executor:{kind:'agent',role:'engineering',skill:'implementation'},phase_bindings:{}}]});const error=await expectCode(()=>f.service.require({lease_ref:a.lease_ref,run_id:'run-1',repository:'laurajoyhutchins/overcenter',transition_id:'transition-a'}),'PROJECT_TRANSITION_AUTHORITY_STALE');assert(error.details?.reason==='dependency-changed','dependency-only revision was not classified fail-closed');});
  await test('authority revision change invalidates an active lease',async()=>{const f=fixture();const a=await f.service.acquire({run_id:'run-1',project_ref:'github:laurajoyhutchins/overcenter',transition_id:'transition-a',lease_seconds:600,idempotency_key:'a'});f.setGraph({...f.graph,authority:{...f.graph.authority,definition:{...f.graph.authority.definition,revision:'2'.repeat(40)}}});await expectCode(()=>f.service.require({lease_ref:a.lease_ref,run_id:'run-1',repository:'laurajoyhutchins/overcenter',transition_id:'transition-a'}),'PROJECT_TRANSITION_AUTHORITY_STALE');});
  await test('execution authority resolves project transition lease refs with no lane or Linear adapter',async()=>{const f=executionAuthorityFixture();const r=await f.service.require({lease_ref:f.leaseRef,repository:f.repository});const counts=f.counts();assert(r.subject==='project_transition'&&r.transition_id==='transition-a','project transition authority evidence missing');assert(!('gate' in r)&&!('work_ref' in r),'graph authority leaked legacy work identity');assert(counts.projectTransitionReads===1,'graph authority validator was not consulted exactly once');});
  await test('durable work-lease encoding preserves graph identity without lane semantics or leaking capability material',async()=>{const semantic={lease_id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',subject:'project_transition',run_id:'run-1',project_ref:'github:laurajoyhutchins/overcenter',transition_id:'transition-a',repository:'laurajoyhutchins/overcenter',authority_revision:'1'.repeat(40),authority_derivation:'overcenter-project-graph-v1',graph_fingerprint:'f'.repeat(64),transition_definition_fingerprint:'d'.repeat(64),transition_revision_fingerprint:'b'.repeat(64),transition_dependency_fingerprint:'c'.repeat(64),slot_key:'project_transition:github:laurajoyhutchins/overcenter:'+ '1'.repeat(40)+':transition-a',status:'active',created_at:'2026-08-27T13:00:00Z',expires_at:'2026-08-27T13:30:00Z',hard_expires_at:'2026-08-27T14:00:00Z',acquire_idempotency_key:'persist',acquire_request_hash:'e'.repeat(64)};const prepared=await prepareProjectTransitionLeasePersistence(semantic,{capabilityToken:'internal-secret'});assert(prepared.work_ref===semantic.slot_key&&prepared.gate==='project_transition'&&!prepared.gate.startsWith('lane:'),'durable project-transition storage resurrected lane semantics');assert(prepared.claim_idempotency_key==='project-transition:persist','idempotency namespace is not isolated');assert(prepared.claim_receipt.subject==='project_transition'&&!JSON.stringify(prepared.claim_receipt).includes('internal-secret'),'durable receipt leaked capability');const restored=restoreProjectTransitionLease({lease_id:semantic.lease_id,work_ref:prepared.work_ref,gate:prepared.gate,run_id:semantic.run_id,status:'active',created_at:semantic.created_at,expires_at:semantic.expires_at,hard_expires_at:semantic.hard_expires_at,claim_idempotency_key:prepared.claim_idempotency_key,claim_request_hash:semantic.acquire_request_hash,claim_receipt:prepared.claim_receipt,settle_idempotency_key:null,settle_plan:null,settled_at:null});assert(restored.project_ref===semantic.project_ref&&restored.transition_id===semantic.transition_id&&restored.acquire_idempotency_key==='persist','durable graph identity did not round-trip');assert(restored.transition_definition_fingerprint===semantic.transition_definition_fingerprint,'transition-definition fingerprint did not round-trip');assert(restored.transition_revision_fingerprint===semantic.transition_revision_fingerprint,'transition-revision fingerprint did not round-trip');assert(restored.transition_dependency_fingerprint===semantic.transition_dependency_fingerprint,'transition-dependency fingerprint did not round-trip');});
  await test('postgres adapter scopes graph lease reads to the project-transition subject namespace without lane values',async()=>{const calls=[];const db={async query(sql,params){calls.push({sql,params});return{rows:[]};}};const store=createProjectTransitionLeasePostgresStore(db,{capabilityFactory:()=> 'private-capability'});await store.getLease('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb');await store.getLeaseByAcquireIdempotency('persist');await store.getSlot('project-transition-slot');await store.getRun('run-1');assert(calls.some(call=>call.sql.includes("claim_receipt->>'subject' = 'project_transition'")),'lease read was not subject-scoped');assert(calls.some(call=>call.params?.includes('project-transition:persist')),'idempotency namespace was not used');assert(calls.some(call=>call.params?.includes('project_transition')),'slot read lost project-transition storage scope');assert(!calls.some(call=>call.params?.some(value=>String(value).startsWith('lane:'))),'graph persistence consulted a legacy lane value');});
  await test('bootstrap confirmation emits normal transition settlement then observes successor frontier',async()=>{
    const createBootstrap=projectTransitionLeases.createProjectGraphDeriverBootstrapConfirmationService;
    assert(typeof createBootstrap==='function','bootstrap confirmation service is missing');
    const responsibilities=responsibilitiesFor('ENABLE');
    const completed=Object.fromEntries(PRODUCTIVE_STAGES.map(stage=>[stage,{applicable:true,satisfied:true}]));
    const first={id:'register-project-graph-deriver',priority:120,requires:[],lifecycle:{current_stage:'ENABLE',responsibilities},executor:{kind:'agent',role:'implementation',skill:'test-driven-development'},phase_bindings:{}};
    const successor={id:'require-production-reachability',priority:110,requires:['register-project-graph-deriver'],lifecycle:{current_stage:'ENABLE',responsibilities},executor:{kind:'agent',role:'implementation',skill:'test-driven-development'},phase_bindings:{}};
    const authority={definition:{kind:'github',repository:'laurajoyhutchins/overcenter',revision:'a'.repeat(40),derivation:'overcenter-project-graph-v1'},observations:[]};
    const ready={schema:'project-graph-authority-v1',project_ref:'github:laurajoyhutchins/overcenter',authority,nodes:[first,successor],horizons:[]};
    const done={...ready,nodes:[{...first,lifecycle:{current_stage:'CONFIRM',condition:'NOMINAL',responsibilities:completed}},successor]};
    const fingerprint=await projectTransitionDefinitionFingerprint(first);
    let reads=0; const calls=[];
    const projectTransitions={
      async acquire(input){calls.push(['acquire',input]);return{ok:true,lease_ref:'00000000-0000-4000-8000-00000000beef',transition_definition_fingerprint:fingerprint,authority:authority.definition};},
      async settle(input){calls.push(['settle',input]);return{ok:true,status:'settled',disposition:'completed',settled_at:'2026-08-29T05:20:00Z'};},
    };
    const service=createBootstrap({projectTransitions,readProjectGraph:async()=>{reads+=1;return reads===1?ready:done;}});
    const result=await service.confirm({run_id:'bootstrap-confirm-run'});
    assert(result.ok&&result.outcome==='confirmed','bootstrap confirmation did not return confirmed');
    assert(result.transition_id==='register-project-graph-deriver'&&result.transition_definition_fingerprint===fingerprint,'bootstrap confirmation lost stable transition identity');
    assert(result.frontier.includes('require-production-reachability'),'bootstrap confirmation did not observe successor frontier');
    assert(calls[0][0]==='acquire'&&calls[0][1].project_ref==='github:laurajoyhutchins/overcenter'&&calls[0][1].transition_id==='register-project-graph-deriver','bootstrap confirmation did not acquire fixed graph transition authority');
    assert(calls[1][0]==='settle'&&calls[1][1].disposition==='completed','bootstrap confirmation did not emit normal completed settlement');
    assert(!('project_ref' in calls[0][1] && calls[0][1].project_ref!=='github:laurajoyhutchins/overcenter'),'caller authority reached transition acquisition');
  });
  return{ok:tests.every(x=>x.ok),passed:tests.filter(x=>x.ok).length,failed:tests.filter(x=>!x.ok).length,tests};
}