import { createProjectAuthoringRecoveryService } from './project-authoring-recovery.js';
import { createProjectAuthoringRecoveryForRuntime } from './project-authoring-overcenter-host.js';
function check(v,m){if(!v)throw new Error(m);}
function base(){return{command:'project.amend',project_ref:'github:laurajoyhutchins/overcenter',idempotency_key:'project-amend-v1:test',request_sha256:'a'.repeat(64),expected_revision:'1'.repeat(40),staged_revision:'2'.repeat(40),pull_request:42,waiting_on:['checks']};}
function store(){let row=null;return{async claim(i){if(!row){row={operation_id:'op-1',state:'prepared',request_sha256:i.request_sha256,recovery_payload:{...i.recovery_payload,attempt_token:i.attempt_token},resolution:null};return{outcome:'claimed',operation:row};}if(row.request_sha256!==i.request_sha256)return{outcome:'conflict',operation:row};if(['succeeded','no_effect','rejected'].includes(row.state))return{outcome:'terminal',operation:row};if(row.state==='indeterminate')return{outcome:'indeterminate',operation:row};if(row._claimed)return{outcome:'in_progress',operation:row};row={...row,recovery_payload:{...row.recovery_payload,attempt_token:i.attempt_token},_claimed:true};return{outcome:'claimed',recovered:true,operation:row};},async updateRecovery(i){row={...row,state:'prepared',recovery_payload:{...i.recovery_payload,attempt_token:i.attempt_token},_claimed:false};return row;},async markIndeterminate(i){row={...row,state:'indeterminate',may_have_mutated:true,recovery_payload:{...i.recovery_payload,attempt_token:i.attempt_token},_claimed:false};return row;},async succeed(i){row={...row,state:'succeeded',may_have_mutated:i.may_have_mutated,recovery_payload:null,resolution:i.resolution,_claimed:false};return row;},row(){return row;},release(){if(row)row._claimed=false;}};}
function svc(overrides={}){const ops=overrides.operations||store();let tick=0;return{ops,service:createProjectAuthoringRecoveryService({operations:ops,now:()=>new Date(Date.UTC(2026,8,9,14,0,++tick)).toISOString(),uuid:()=>`attempt-${tick}`,inspectCandidate:overrides.inspectCandidate||(async()=>({outcome:'waiting',waiting_on:['checks']})),integrateCandidate:overrides.integrateCandidate||(async()=>({ok:true,outcome:'merged'})),readAuthoritativeProject:overrides.readAuthoritativeProject||(async()=>({confirmed:true,authority_revision:'3'.repeat(40)})),listPending:overrides.listPending})};}
async function t(name,fn){try{await fn();return{name,ok:true};}catch(e){return{name,ok:false,error:String(e?.message||e)};}}
export async function runProjectAuthoringRecoveryTests(){const r=[];
r.push(await t('begin persists wait without reconciliation providers',async()=>{const ops=store();const service=createProjectAuthoringRecoveryService({operations:ops,now:()=>new Date(Date.UTC(2026,8,9,14,0,1)).toISOString(),uuid:()=>`attempt-begin`});const x=await service.begin(base());check(x.outcome==='WAITING_EXTERNAL_VERIFICATION','begin required reconciliation providers');check(ops.row().recovery_payload.pull_request===42,'begin lost candidate identity');}));
r.push(await t('persists truthful external verification wait',async()=>{const{ops,service}=svc();const x=await service.begin(base());check(x.outcome==='WAITING_EXTERNAL_VERIFICATION','wrong wait outcome');check(ops.row().recovery_payload.staged_revision==='2'.repeat(40),'lost staged head');check(ops.row().recovery_payload.pull_request===42,'lost PR identity');}));
r.push(await t('pending exact-head verification remains waiting',async()=>{const{ops,service}=svc({inspectCandidate:async()=>({outcome:'waiting',waiting_on:['required_checks','mergeability']})});await service.begin(base());ops.release();const x=await service.reconcile(base());check(x.outcome==='WAITING_EXTERNAL_VERIFICATION','pending CI not waiting');check(x.waiting_on.join(',')==='mergeability,required_checks','waiting predicates unstable');}));
r.push(await t('ready candidate integrates once and terminal replay is exact',async()=>{let merges=0;const{ops,service}=svc({inspectCandidate:async()=>({outcome:'ready'}),integrateCandidate:async()=>{merges++;return{ok:true,outcome:'merged'};}});await service.begin(base());ops.release();const x=await service.reconcile(base());check(x.state==='succeeded','did not succeed');const y=await service.reconcile(base());check(y.idempotent_replay&&merges===1,'terminal replay retriggered integration');}));
r.push(await t('duplicate wakeup cannot integrate concurrently',async()=>{let release,merges=0;const{ops,service}=svc({inspectCandidate:async()=>({outcome:'ready'}),integrateCandidate:async()=>{merges++;await new Promise(res=>release=res);return{ok:true,outcome:'merged'};}});await service.begin(base());ops.release();const first=service.reconcile(base());await new Promise(res=>setTimeout(res,0));const second=await service.reconcile(base());check(second.outcome==='RECOVERY_IN_PROGRESS','duplicate wake acquired ownership');release();await first;check(merges===1,'integrated twice');}));
for(const outcome of ['base_moved','head_moved','closed','replaced','policy_ambiguous','recompute_required'])r.push(await t(`${outcome} enters recompute`,async()=>{const{ops,service}=svc({inspectCandidate:async()=>({outcome})});await service.begin(base());ops.release();const x=await service.reconcile(base());check(x.outcome==='RECOMPUTE_REQUIRED',`${outcome} misclassified`);}));
r.push(await t('failed checks become verification failure',async()=>{const{ops,service}=svc({inspectCandidate:async()=>({outcome:'failed_verification'})});await service.begin(base());ops.release();const x=await service.reconcile(base());check(x.outcome==='VERIFICATION_FAILED','failed checks misclassified');}));
r.push(await t('integration transport ambiguity becomes indeterminate',async()=>{const e=Object.assign(new Error('lost response'),{may_have_mutated:true});const{ops,service}=svc({inspectCandidate:async()=>({outcome:'ready'}),integrateCandidate:async()=>{throw e;}});await service.begin(base());ops.release();const x=await service.reconcile(base());check(x.state==='indeterminate'&&x.outcome==='INDETERMINATE_INTEGRATION','ambiguity not durable');}));
r.push(await t('final readback mismatch becomes indeterminate',async()=>{const{ops,service}=svc({inspectCandidate:async()=>({outcome:'ready'}),readAuthoritativeProject:async()=>({confirmed:false})});await service.begin(base());ops.release();const x=await service.reconcile(base());check(x.state==='indeterminate'&&x.outcome==='INDETERMINATE_READBACK','readback mismatch not durable');}));
r.push(await t('maintenance recovery handles missed events',async()=>{let seen=0;const{service}=svc({listPending:async()=>[base()],inspectCandidate:async()=>{seen++;return{outcome:'waiting',waiting_on:['checks']};}});const x=await service.reconcilePending();check(x.length===1&&seen===1,'maintenance missed pending work');}));
r.push(await t('production recovery factory drives pending authoring through authoritative readback',async()=>{const ops=store();let authorityReads=0,inspections=0,integrations=0,graphReads=0;const definition={schema:'overcenter-project-definition-v1',project_ref:'github:laurajoyhutchins/overcenter',transitions:[{id:'recovery-proof',priority:1,requires:[],executor:{kind:'agent',role:'verification',skill:'prove recovery'}}]};const graphRuntime={async resolveProjectAuthority(){authorityReads++;return{kind:'github',repository:'laurajoyhutchins/overcenter',project_ref:'github:laurajoyhutchins/overcenter',branch:'dev',revision:authorityReads===1?'1'.repeat(40):'3'.repeat(40),derivation:'overcenter-project-graph-v1'};},async readProjectFacts({revision}){return{schema:'project-authority-facts-v1',repository:'laurajoyhutchins/overcenter',revision,facts:{definition_facts:{definitions:[{path:'.overcenter/definitions/overcenter.json',content:JSON.stringify(definition)}]}}};}};const recovery=createProjectAuthoringRecoveryForRuntime({db:{},withGitHubAppApiClient:async()=>{}},{operations:ops,graphRuntime,inspectIntegration:async()=>{inspections++;return{ok:true,outcome:'ready',pull_request:42,expected_head:'2'.repeat(40)};},integrateCandidate:async()=>{integrations++;return{ok:true,outcome:'merged',merge_commit_sha:'3'.repeat(40)};},deriveProjectGraph:async()=>{graphReads++;return{project_ref:'github:laurajoyhutchins/overcenter',revision:'3'.repeat(40),nodes:[]};}});await recovery.begin(base());ops.release();const x=await recovery.reconcilePending({limit:5});check(x.length===1&&x[0].state==='succeeded','pending authoring did not terminalize');check(inspections===1&&integrations===1,'factory did not own inspect/integration');check(authorityReads>=2&&graphReads===1,'factory did not perform final authoritative readback');}));
return{ok:r.every(x=>x.ok),passed:r.filter(x=>x.ok).length,failed:r.filter(x=>!x.ok).length,results:r};}
runProjectAuthoringRecoveryTests().then((result)=>{console.log(JSON.stringify(result,null,2));if(!result.ok)process.exitCode=1;}).catch((error)=>{console.error(error);process.exitCode=1;});