import { createRepositoryLifecycleService, repositoryHealthProjection } from './repository-disposition.js';
import { rewriteRepositoryCoordinate } from './repository-identity.js';

function assert(value, message) { if (!value) throw new Error(message); }
function clone(value) { return JSON.parse(JSON.stringify(value)); }

class MemoryStore {
  constructor() { this.rows = new Map(); this.work = new Map(); }
  async get(repository) { return this.rows.get(repository.toLowerCase()) || null; }
  async getByGitHubRepositoryId(id) { return [...this.rows.values()].find(row => Number(row.github_repository_id) === Number(id)) || null; }
  async bindGitHubRepositoryId(repository,id) { const row=await this.get(repository); if (!row) return null; row.github_repository_id=Number(id); this.rows.set(repository.toLowerCase(),clone(row)); return this.get(repository); }
  async put(row) {
    const current=await this.get(row.repository);
    if (current?.github_repository_id != null && row.github_repository_id != null && Number(current.github_repository_id)!==Number(row.github_repository_id)) throw Object.assign(new Error('coordinate conflict'),{code:'REPOSITORY_IDENTITY_COORDINATE_CONFLICT'});
    this.rows.set(row.repository.toLowerCase(),clone(row)); return this.get(row.repository);
  }
  async listWorkIdentities(repository) { return clone(this.work.get(repository.toLowerCase()) || []); }
  async rebindRepositoryIdentity({github_repository_id,from_repository,to_repository,updated_at}) {
    const row=await this.get(from_repository); if (!row || Number(row.github_repository_id)!==Number(github_repository_id)) return null;
    if (await this.get(to_repository)) throw new Error('target exists');
    this.rows.delete(from_repository.toLowerCase()); row.repository=to_repository; row.updated_at=updated_at; this.rows.set(to_repository.toLowerCase(),clone(row));
    const work=this.work.get(from_repository.toLowerCase()) || []; this.work.delete(from_repository.toLowerCase());
    this.work.set(to_repository.toLowerCase(), work.map(item => ({...item,source_repo:to_repository,source_key:item.source_kind==='github_issue'&&item.source_issue_number?`github:${to_repository}#issue:${item.source_issue_number}`:item.source_key})));
    return this.get(to_repository);
  }
}

class FakeGithub {
  constructor(archived=false, id=101, names={}) { this.archived=archived; this.id=id; this.names=names; this.calls=0; }
  async getRepository(repository) { this.calls+=1; return { id:this.id, full_name:this.names[repository.toLowerCase()] || repository, archived:this.archived }; }
}

class FakeProjection {
  constructor() { this.calls=[]; }
  async rebind(work,from,to) { this.calls.push({work:clone(work),from,to}); return work.map(item=>item.linear_identifier).filter(Boolean); }
}

export async function runRepositoryDispositionTests() {
  const tests=[]; async function test(name,fn){try{await fn();tests.push({name,ok:true});}catch(error){tests.push({name,ok:false,error:String(error?.message||error)});}}

  await test('GitHub archived evidence deterministically yields ARCHIVED', async()=>{const service=createRepositoryLifecycleService({store:new MemoryStore(),github:new FakeGithub(true),now:()=> '2026-08-22T16:00:00.000Z'});const row=await service.observe('Owner/Repo');assert(row.disposition==='ARCHIVED'&&!row.ordinary_work_enabled&&row.github_archived,'GitHub archive did not dispose repository');});
  await test('GitHub archive overrides a stale ACTIVE record', async()=>{const store=new MemoryStore();await store.put({repository:'owner/repo',github_repository_id:101,disposition:'ACTIVE',successor_repository:null,github_archived:false});const service=createRepositoryLifecycleService({store,github:new FakeGithub(true),now:()=> '2026-08-22T16:00:00.000Z'});const row=await service.observe('owner/repo');assert(row.disposition==='ARCHIVED'&&!row.ordinary_work_enabled,'archived GitHub repository remained ACTIVE');});
  await test('external unarchive cannot reactivate disposed repository', async()=>{const store=new MemoryStore();await store.put({repository:'owner/repo',github_repository_id:101,disposition:'ARCHIVED',successor_repository:null,github_archived:true});const service=createRepositoryLifecycleService({store,github:new FakeGithub(false),now:()=> '2026-08-22T16:00:00.000Z'});const row=await service.observe('owner/repo');assert(row.disposition==='ARCHIVED'&&!row.ordinary_work_enabled&&!row.github_archived,'external unarchive silently reactivated repository');});
  await test('explicit lifecycle transition can restore an unarchived repository', async()=>{const store=new MemoryStore();await store.put({repository:'owner/repo',github_repository_id:101,disposition:'ARCHIVED',successor_repository:null,github_archived:true});const service=createRepositoryLifecycleService({store,github:new FakeGithub(false),now:()=> '2026-08-22T16:00:00.000Z'});const row=await service.transition({repository:'owner/repo',disposition:'ACTIVE',expected_disposition:'ARCHIVED',reason:'owner-approved reactivation'});assert(row.disposition==='ACTIVE'&&row.ordinary_work_enabled,'explicit transition did not restore ACTIVE');});
  await test('SUPERSEDED is terminal for ordinary work and routes to successor', async()=>{const store=new MemoryStore();const service=createRepositoryLifecycleService({store,github:new FakeGithub(true),now:()=> '2026-08-22T16:00:00.000Z'});const row=await service.dispose({repository:'owner/old',disposition:'SUPERSEDED',successor_repository:'owner/new',reason:'responsibility moved'});assert(row.disposition==='SUPERSEDED'&&row.successor_repository==='owner/new'&&!row.ordinary_work_enabled,'superseded routing semantics incorrect');});
  await test('legacy compatibility-bound disposal cannot be resurrected', async()=>{const service=createRepositoryLifecycleService({store:new MemoryStore(),github:new FakeGithub(true),now:()=> '2026-08-22T16:00:00.000Z'});let failure=null;try{await service.dispose({repository:'owner/bridge',disposition:'ARCHIVED',compatibility_bound:true});}catch(error){failure=error;}assert(failure?.code==='LEGACY_CONTROL_PLANE_RETIRED',`legacy compatibility bound was not rejected: ${failure?.code}`);});
  await test('disposal is idempotent for identical semantics', async()=>{const store=new MemoryStore();const service=createRepositoryLifecycleService({store,github:new FakeGithub(true),now:()=> '2026-08-22T16:00:00.000Z'});const a=await service.dispose({repository:'owner/repo',disposition:'ARCHIVED',reason:'retired'});const b=await service.dispose({repository:'owner/repo',disposition:'ARCHIVED',reason:'retired'});assert(a.disposition===b.disposition&&b.changed===false,'repeated disposal was not idempotent');});
  await test('DORMANT is intentionally non-executable without becoming historical disposal', async()=>{const store=new MemoryStore();await store.put({repository:'owner/repo',github_repository_id:101,disposition:'ACTIVE',successor_repository:null,github_archived:false});const service=createRepositoryLifecycleService({store,github:new FakeGithub(false),now:()=> '2026-08-22T16:00:00.000Z'});const row=await service.transition({repository:'owner/repo',disposition:'DORMANT',expected_disposition:'ACTIVE',reason:'parked'});assert(!row.ordinary_work_enabled&&!row.fast_forward_eligible&&!row.scheduled_worker_target,'DORMANT remained executable');assert(row.health.classification==='dormant_as_intended'&&!row.health.include_in_active_health,'DORMANT leaked into active health');});
  await test('controls projection maps every repository disposition onto power state and permissives', async()=>{for(const [disposition,githubArchived,power,disconnect,enabled] of [['ACTIVE',false,'ENERGIZED','CLOSED',true],['MAINTENANCE',false,'ENERGIZED','CLOSED',true],['DORMANT',false,'DE_ENERGIZED','OPEN',false],['ARCHIVED',true,'DE_ENERGIZED','OPEN',false],['SUPERSEDED',true,'DE_ENERGIZED','OPEN',false]]){const store=new MemoryStore();await store.put({repository:'owner/repo',github_repository_id:101,disposition,successor_repository:disposition==='SUPERSEDED'?'owner/new':null,github_archived:githubArchived});const row=await createRepositoryLifecycleService({store,github:new FakeGithub(githubArchived),now:()=> '2026-08-22T16:00:00.000Z'}).observe('owner/repo');assert(row.controls?.power_state===power&&row.controls?.disconnect_position===disconnect&&row.controls?.permissives?.ordinary_work===enabled,`${disposition} controls projection diverged`);}});
  await test('repository status exposes controls projection', async()=>{const store=new MemoryStore();await store.put({repository:'owner/repo',github_repository_id:101,disposition:'DORMANT',successor_repository:null,github_archived:false});const status=await createRepositoryLifecycleService({store,github:new FakeGithub(false)}).verify('owner/repo');assert(status.controls?.power_state==='DE_ENERGIZED'&&!status.controls?.permissives?.ordinary_work,'status omitted controls projection');});
  await test('lifecycle transition returns command-envelope-compatible success', async()=>{const store=new MemoryStore();await store.put({repository:'owner/repo',github_repository_id:101,disposition:'ACTIVE',successor_repository:null,github_archived:false});const row=await createRepositoryLifecycleService({store,github:new FakeGithub(false)}).transition({repository:'owner/repo',disposition:'DORMANT',expected_disposition:'ACTIVE'});assert(row.ok===true,'transition cannot be accepted by command envelope');});
  await test('disposed repository health is intentional preservation state', async()=>{const health=repositoryHealthProjection({disposition:'ARCHIVED'});assert(health.classification==='disposed_as_intended'&&!health.include_in_active_health,'disposed repository leaked into active health');});

  await test('legacy lifecycle rows are backfilled with immutable GitHub repository id', async()=>{const store=new MemoryStore();await store.put({repository:'owner/repo',disposition:'DORMANT',successor_repository:null,github_archived:false});const row=await createRepositoryLifecycleService({store,github:new FakeGithub(false,444)}).observe('owner/repo');assert(row.github_repository_id===444&&row.disposition==='DORMANT','legacy row was not identity-bound without changing lifecycle');});
  await test('DORMANT rename preserves lifecycle and migrates durable work identity', async()=>{const store=new MemoryStore();await store.put({repository:'owner/old',github_repository_id:444,disposition:'DORMANT',successor_repository:null,github_archived:false});store.work.set('owner/old',[{source_kind:'github_issue',source_repo:'owner/old',source_issue_number:7,source_key:'github:owner/old#issue:7',linear_issue_id:'lin-7',linear_identifier:'LJH-7'}]);const projection=new FakeProjection();const github=new FakeGithub(false,444,{'owner/new':'owner/new'});const row=await createRepositoryLifecycleService({store,github,coordinateProjection:projection,now:()=> '2026-08-23T18:00:00.000Z'}).observe('owner/new');assert(row.repository==='owner/new'&&row.github_repository_id===444&&row.disposition==='DORMANT','rename changed DORMANT lifecycle');const work=await store.listWorkIdentities('owner/new');assert(work[0].source_key==='github:owner/new#issue:7'&&work[0].linear_identifier==='LJH-7','durable work identity did not move without duplication');assert(projection.calls.length===1&&projection.calls[0].from==='owner/old'&&projection.calls[0].to==='owner/new','Linear coordinate projection was not reconciled');});
  await test('ACTIVE rename preserves executable lifecycle', async()=>{const store=new MemoryStore();await store.put({repository:'owner/old',github_repository_id:444,disposition:'ACTIVE',successor_repository:null,github_archived:false});const row=await createRepositoryLifecycleService({store,github:new FakeGithub(false,444),coordinateProjection:new FakeProjection()}).observe('owner/new');assert(row.repository==='owner/new'&&row.disposition==='ACTIVE'&&row.ordinary_work_enabled,'ACTIVE rename changed lifecycle semantics');});
  await test('old-name reuse by a different GitHub repository id fails closed', async()=>{const store=new MemoryStore();await store.put({repository:'owner/reused',github_repository_id:444,disposition:'DORMANT',successor_repository:null,github_archived:false});let failure=null;try{await createRepositoryLifecycleService({store,github:new FakeGithub(false,999)}).observe('owner/reused');}catch(error){failure=error;}assert(failure?.code==='REPOSITORY_IDENTITY_COORDINATE_CONFLICT','replacement repository inherited stale lifecycle instead of failing closed');});
  await test('direct Linear repository coordinates rewrite without changing surrounding text', async()=>{const direct='Outcome: keep this\n\nRepository: `owner/old`\n\nNext action: continue';const heading='## Repository\nowner/old\n\n## Outcome\nKeep';assert(rewriteRepositoryCoordinate(direct,'owner/old','owner/new')==='Outcome: keep this\n\nRepository: `owner/new`\n\nNext action: continue','direct coordinate rewrite changed unrelated text');assert(rewriteRepositoryCoordinate(heading,'owner/old','owner/new')==='## Repository\nowner/new\n\n## Outcome\nKeep','heading coordinate rewrite failed');});

  return {ok:tests.every(test=>test.ok),passed:tests.filter(test=>test.ok).length,failed:tests.filter(test=>!test.ok).length,tests};
}