import { createRepositoryLifecycleService, repositoryHealthProjection } from './repository-disposition.js';
import { rewriteRepositoryCoordinate } from './repository-identity.js';

function assert(value,message){if(!value)throw new Error(message);}function clone(value){return JSON.parse(JSON.stringify(value));}
class MemoryStore{constructor(){this.rows=new Map();this.work=new Map();}async get(repository){return this.rows.get(repository.toLowerCase())||null;}async getByGitHubRepositoryId(id){return [...this.rows.values()].find(row=>Number(row.github_repository_id)===Number(id))||null;}async listUnbound(){return [...this.rows.values()].filter(row=>row.github_repository_id==null).map(clone);}async bindGitHubRepositoryId(repository,id){const row=await this.get(repository);if(!row)return null;row.github_repository_id=Number(id);this.rows.set(repository.toLowerCase(),clone(row));return this.get(repository);}async put(row){const current=await this.get(row.repository);if(current?.github_repository_id!=null&&row.github_repository_id!=null&&Number(current.github_repository_id)!==Number(row.github_repository_id))throw Object.assign(new Error('coordinate conflict'),{code:'REPOSITORY_IDENTITY_COORDINATE_CONFLICT'});this.rows.set(row.repository.toLowerCase(),clone(row));return this.get(row.repository);}async listWorkIdentities(repository){return clone(this.work.get(repository.toLowerCase())||[]);}async rebindRepositoryIdentity({github_repository_id,from_repository,to_repository,updated_at}){const row=await this.get(from_repository);if(!row||Number(row.github_repository_id)!==Number(github_repository_id))return null;const target=await this.get(to_repository);if(target&&target!==row)throw new Error('target exists');this.rows.delete(from_repository.toLowerCase());row.repository=to_repository;row.updated_at=updated_at;this.rows.set(to_repository.toLowerCase(),clone(row));const work=this.work.get(from_repository.toLowerCase())||[];this.work.delete(from_repository.toLowerCase());this.work.set(to_repository.toLowerCase(),work.map(item=>({...item,source_repo:to_repository,source_key:item.source_kind==='github_issue'&&item.source_issue_number?`github:${to_repository}#issue:${item.source_issue_number}`:item.source_key})));return this.get(to_repository);}}
class FakeGithub{constructor(archived=false,id=101,names={}){this.archived=archived;this.id=id;this.names=names;this.calls=0;}async getRepository(repository){this.calls+=1;const mapped=this.names[repository.toLowerCase()];if(mapped===null){const error=new Error('not found');error.status=404;throw error;}return{id:this.id,full_name:mapped||repository,archived:this.archived};}}
class MultiGithub{constructor(entries){this.entries=new Map(Object.entries(entries).map(([key,value])=>[key.toLowerCase(),value]));}async getRepository(repository){const entry=this.entries.get(repository.toLowerCase());if(!entry){const error=new Error('not found');error.status=404;throw error;}return clone(entry);}}
class FakeProjection{constructor(){this.calls=[];}async rebind(work,from,to){this.calls.push({work:clone(work),from,to});return work.map(item=>item.linear_identifier).filter(Boolean);}}
export async function runRepositoryDispositionTests(){const tests=[];async function test(name,fn){try{await fn();tests.push({name,ok:true});}catch(error){tests.push({name,ok:false,error:String(error?.message||error)});}}
await test('GitHub archived evidence deterministically yields ARCHIVED',async()=>{const row=await createRepositoryLifecycleService({store:new MemoryStore(),github:new FakeGithub(true),now:()=> '2026-08-22T16:00:00.000Z'}).observe('Owner/Repo');assert(row.disposition==='ARCHIVED'&&!row.ordinary_work_enabled&&row.github_archived,'archive did not dispose repository');});
await test('GitHub archive overrides a stale ACTIVE record',async()=>{const store=new MemoryStore();await store.put({repository:'owner/repo',github_repository_id:101,disposition:'ACTIVE',successor_repository:null,github_archived:false});const row=await createRepositoryLifecycleService({store,github:new FakeGithub(true)}).observe('owner/repo');assert(row.disposition==='ARCHIVED'&&!row.ordinary_work_enabled,'archived repo remained ACTIVE');});
await test('external unarchive cannot reactivate disposed repository',async()=>{const store=new MemoryStore();await store.put({repository:'owner/repo',github_repository_id:101,disposition:'ARCHIVED',successor_repository:null,github_archived:true});const row=await createRepositoryLifecycleService({store,github:new FakeGithub(false)}).observe('owner/repo');assert(row.disposition==='ARCHIVED'&&!row.ordinary_work_enabled&&!row.github_archived,'external unarchive reactivated repository');});
await test('explicit lifecycle transition can restore an unarchived repository',async()=>{const store=new MemoryStore();await store.put({repository:'owner/repo',github_repository_id:101,disposition:'ARCHIVED',successor_repository:null,github_archived:true});const row=await createRepositoryLifecycleService({store,github:new FakeGithub(false)}).transition({repository:'owner/repo',disposition:'ACTIVE',expected_disposition:'ARCHIVED'});assert(row.disposition==='ACTIVE'&&row.ordinary_work_enabled,'explicit transition failed');});
await test('SUPERSEDED is terminal for ordinary work and routes to successor',async()=>{const row=await createRepositoryLifecycleService({store:new MemoryStore(),github:new FakeGithub(true)}).dispose({repository:'owner/old',disposition:'SUPERSEDED',successor_repository:'owner/new'});assert(row.disposition==='SUPERSEDED'&&row.successor_repository==='owner/new'&&!row.ordinary_work_enabled,'superseded semantics incorrect');});
await test('legacy compatibility-bound disposal cannot be resurrected',async()=>{let failure=null;try{await createRepositoryLifecycleService({store:new MemoryStore(),github:new FakeGithub(true)}).dispose({repository:'owner/bridge',disposition:'ARCHIVED',compatibility_bound:true});}catch(error){failure=error;}assert(failure?.code==='LEGACY_CONTROL_PLANE_RETIRED','legacy compatibility was not rejected');});
await test('disposal is idempotent for identical semantics',async()=>{const store=new MemoryStore();const service=createRepositoryLifecycleService({store,github:new FakeGithub(true),now:()=> '2026-08-22T16:00:00.000Z'});const a=await service.dispose({repository:'owner/repo',disposition:'ARCHIVED',reason:'retired'});const b=await service.dispose({repository:'owner/repo',disposition:'ARCHIVED',reason:'retired'});assert(a.disposition===b.disposition&&b.changed===false,'disposal not idempotent');});
await test('DORMANT is intentionally non-executable',async()=>{const store=new MemoryStore();await store.put({repository:'owner/repo',github_repository_id:101,disposition:'ACTIVE',successor_repository:null,github_archived:false});const row=await createRepositoryLifecycleService({store,github:new FakeGithub(false)}).transition({repository:'owner/repo',disposition:'DORMANT',expected_disposition:'ACTIVE'});assert(!row.ordinary_work_enabled&&!row.fast_forward_eligible&&!row.scheduled_worker_target&&row.health.classification==='dormant_as_intended','DORMANT remained executable');});
await test('controls projection maps every repository disposition',async()=>{for(const [disposition,archived,power,enabled]of[['ACTIVE',false,'ENERGIZED',true],['MAINTENANCE',false,'ENERGIZED',true],['DORMANT',false,'DE_ENERGIZED',false],['ARCHIVED',true,'DE_ENERGIZED',false],['SUPERSEDED',true,'DE_ENERGIZED',false]]){const store=new MemoryStore();await store.put({repository:'owner/repo',github_repository_id:101,disposition,successor_repository:disposition==='SUPERSEDED'?'owner/new':null,github_archived:archived});const row=await createRepositoryLifecycleService({store,github:new FakeGithub(archived)}).observe('owner/repo');assert(row.controls?.power_state===power&&row.controls?.permissives?.ordinary_work===enabled,`${disposition} controls diverged`);}});
await test('lifecycle transition returns command-envelope-compatible success',async()=>{const store=new MemoryStore();await store.put({repository:'owner/repo',github_repository_id:101,disposition:'ACTIVE',github_archived:false});const row=await createRepositoryLifecycleService({store,github:new FakeGithub(false)}).transition({repository:'owner/repo',disposition:'DORMANT',expected_disposition:'ACTIVE'});assert(row.ok===true,'transition envelope incompatible');});
await test('disposed repository health is intentional preservation state',async()=>{const health=repositoryHealthProjection({disposition:'ARCHIVED'});assert(health.classification==='disposed_as_intended'&&!health.include_in_active_health,'disposed health wrong');});
await test('legacy lifecycle rows are backfilled with immutable GitHub repository id',async()=>{const store=new MemoryStore();await store.put({repository:'owner/repo',disposition:'DORMANT',github_archived:false});const row=await createRepositoryLifecycleService({store,github:new FakeGithub(false,444)}).observe('owner/repo');assert(row.github_repository_id===444&&row.disposition==='DORMANT','legacy row identity binding changed lifecycle');});
await test('legacy row renamed before first post-migration observation is discovered and rebound',async()=>{const store=new MemoryStore();await store.put({repository:'owner/old',disposition:'DORMANT',github_archived:false});store.work.set('owner/old',[{source_kind:'github_issue',source_repo:'owner/old',source_issue_number:7,source_key:'github:owner/old#issue:7',linear_issue_id:'lin-7',linear_identifier:'LJH-7'}]);const github=new MultiGithub({'owner/new':{id:444,full_name:'owner/new',archived:false},'owner/old':{id:444,full_name:'owner/new',archived:false}});const projection=new FakeProjection();const row=await createRepositoryLifecycleService({store,github,coordinateProjection:projection}).observe('owner/new');assert(row.repository==='owner/new'&&row.github_repository_id===444&&row.disposition==='DORMANT','pre-backfill rename created a fresh lifecycle');assert((await store.listWorkIdentities('owner/new'))[0].source_key==='github:owner/new#issue:7','work identity did not follow discovered rename');});
await test('DORMANT rename preserves lifecycle and migrates durable work identity',async()=>{const store=new MemoryStore();await store.put({repository:'owner/old',github_repository_id:444,disposition:'DORMANT',github_archived:false});store.work.set('owner/old',[{source_kind:'github_issue',source_repo:'owner/old',source_issue_number:7,source_key:'github:owner/old#issue:7',linear_issue_id:'lin-7',linear_identifier:'LJH-7'}]);const projection=new FakeProjection();const row=await createRepositoryLifecycleService({store,github:new MultiGithub({'owner/new':{id:444,full_name:'owner/new',archived:false}}),coordinateProjection:projection}).observe('owner/new');assert(row.repository==='owner/new'&&row.disposition==='DORMANT','rename changed DORMANT');const work=await store.listWorkIdentities('owner/new');assert(work[0].source_key==='github:owner/new#issue:7'&&work[0].linear_identifier==='LJH-7','durable identity duplicated or changed');assert(projection.calls.length===1,'Linear projection not reconciled');});
await test('ACTIVE rename preserves executable lifecycle',async()=>{const store=new MemoryStore();await store.put({repository:'owner/old',github_repository_id:444,disposition:'ACTIVE',github_archived:false});const row=await createRepositoryLifecycleService({store,github:new MultiGithub({'owner/new':{id:444,full_name:'owner/new',archived:false}}),coordinateProjection:new FakeProjection()}).observe('owner/new');assert(row.repository==='owner/new'&&row.disposition==='ACTIVE'&&row.ordinary_work_enabled,'ACTIVE rename changed lifecycle');});
await test('old-name reuse by a different GitHub repository id fails closed',async()=>{const store=new MemoryStore();await store.put({repository:'owner/reused',github_repository_id:444,disposition:'DORMANT',github_archived:false});let failure=null;try{await createRepositoryLifecycleService({store,github:new FakeGithub(false,999)}).observe('owner/reused');}catch(error){failure=error;}assert(failure?.code==='REPOSITORY_IDENTITY_COORDINATE_CONFLICT','replacement inherited stale lifecycle');});
await test('direct Linear repository coordinates rewrite without changing surrounding text',async()=>{const direct='Outcome: keep this\n\nRepository: `owner/old`\n\nNext action: continue';const heading='## Repository\nowner/old\n\n## Outcome\nKeep';assert(rewriteRepositoryCoordinate(direct,'owner/old','owner/new')==='Outcome: keep this\n\nRepository: `owner/new`\n\nNext action: continue','direct rewrite changed unrelated text');assert(rewriteRepositoryCoordinate(heading,'owner/old','owner/new')==='## Repository\nowner/new\n\n## Outcome\nKeep','heading rewrite failed');});
return{ok:tests.every(test=>test.ok),passed:tests.filter(test=>test.ok).length,failed:tests.filter(test=>!test.ok).length,tests};}