const HASH_LENGTH = 32;
function concatBytes(...arrays){const length=arrays.reduce((sum,value)=>sum+value.length,0);const out=new Uint8Array(length);let offset=0;for(const value of arrays){out.set(value,offset);offset+=value.length;}return out;}
function xorBytes(a,b){if(a.length!==b.length)throw new Error('RSA-OAEP xor length mismatch');const out=new Uint8Array(a.length);for(let i=0;i<a.length;i+=1)out[i]=a[i]^b[i];return out;}
function base64Url(bytes){let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');}
function fromBase64Url(value){if(typeof value!=='string'||!/^[A-Za-z0-9_-]+$/.test(value))throw new Error('Invalid base64url value');const normalized=value.replace(/-/g,'+').replace(/_/g,'/');const padded=normalized+'='.repeat((4-normalized.length%4)%4);const binary=atob(padded);const out=new Uint8Array(binary.length);for(let i=0;i<binary.length;i+=1)out[i]=binary.charCodeAt(i);return out;}
function bytesToBigInt(bytes){let value=0n;for(const byte of bytes)value=(value<<8n)|BigInt(byte);return value;}
function bigIntToBytes(value,length){const out=new Uint8Array(length);let current=value;for(let i=length-1;i>=0;i-=1){out[i]=Number(current&0xffn);current>>=8n;}if(current!==0n)throw new Error('RSA integer exceeds modulus length');return out;}
function modPow(base,exponent,modulus){let result=1n,b=base%modulus,e=exponent;while(e>0n){if(e&1n)result=(result*b)%modulus;e>>=1n;if(e>0n)b=(b*b)%modulus;}return result;}
async function sha256(bytes){return new Uint8Array(await crypto.subtle.digest('SHA-256',bytes));}
async function mgf1(seed,length){const output=new Uint8Array(length);let offset=0;for(let counter=0;offset<length;counter+=1){const c=Uint8Array.of((counter>>>24)&255,(counter>>>16)&255,(counter>>>8)&255,counter&255);const digest=await sha256(concatBytes(seed,c));const take=Math.min(digest.length,length-offset);output.set(digest.subarray(0,take),offset);offset+=take;}return output;}
function parsePublicJwk(jwk){if(!jwk||jwk.kty!=='RSA'||jwk.alg!=='RSA-OAEP-256')throw new Error('Unsupported RSA recipient key');const modulus=fromBase64Url(jwk.n);const exponent=fromBase64Url(jwk.e);if(modulus.length<256)throw new Error('RSA recipient modulus is too short');return{n:bytesToBigInt(modulus),e:bytesToBigInt(exponent),modulusLength:modulus.length};}
export async function rsaOaepEncrypt(jwk,plaintext,label=''){const key=parsePublicJwk(jwk);const message=new TextEncoder().encode(String(plaintext));if(message.length>key.modulusLength-2*HASH_LENGTH-2)throw new Error('RSA-OAEP plaintext is too long');const labelHash=await sha256(new TextEncoder().encode(label));const padding=new Uint8Array(key.modulusLength-message.length-2*HASH_LENGTH-2);const dataBlock=concatBytes(labelHash,padding,Uint8Array.of(1),message);const seed=new Uint8Array(HASH_LENGTH);crypto.getRandomValues(seed);const dbMask=await mgf1(seed,key.modulusLength-HASH_LENGTH-1);const maskedDb=xorBytes(dataBlock,dbMask);const seedMask=await mgf1(maskedDb,HASH_LENGTH);const maskedSeed=xorBytes(seed,seedMask);const encoded=concatBytes(Uint8Array.of(0),maskedSeed,maskedDb);const integer=bytesToBigInt(encoded);if(integer>=key.n)throw new Error('RSA-OAEP encoded message exceeds modulus');return base64Url(bigIntToBytes(modPow(integer,key.e,key.n),key.modulusLength));}
export async function recipientFingerprint(jwk){return base64Url(await sha256(new TextEncoder().encode(`${jwk.n}.${jwk.e}`)));}