import { createWorkLeaseService, createPostgresLeaseStore } from './work-leases.js';

const STATES = [
  { id: 's-backlog', name: 'Backlog', type: 'backlog' },
  { id: 's-done', name: 'Done', type: 'completed' },
  { id: 's-todo', name: 'Todo', type: 'unstarted' },
  { id: 's-progress', name: 'In Progress', type: 'started' },
];
const LABELS = [
  { id: 'l-repo', name: 'lane:repo-implementation' },
  { id: 'l-source', name: 'lane:source-implementation' },
  { id: 'l-verify', name: 'lane:verification' },
  { id: 'l-integrate', name: 'lane:integration' },
];

function lane(issue) { return issue.labels.find(x => x.name.startsWith('lane:')); }
function clone(v) { return JSON.parse(JSON.stringify(v)); }
function semantic(issue) {
  return JSON.stringify({
    title: issue.title,
    description: issue.description || '',
    priority: issue.priority ?? null,
    archivedAt: issue.archivedAt || null,
    project: issue.project || null,
    state: issue.state || null,
    labels: issue.labels || [],
    relations: issue.relations || [],
  });
}
function issue(ref = 'LJH-T1', state = 'Todo', laneName = 'lane:repo-implementation') {
  return {
    id: `uuid-${ref}`, identifier: ref, title: 'Disposable lease test',
    description: 'Repository: `owner/repo`\n\nAuthority: GitHub #1\n\nExact coordinate: test\n\nAcceptance: deterministic\n\nOwner impact: none.',
    priority: 2, updatedAt: 'rev-1', archivedAt: null, project: { id: 'p', name: 'Portfolio Orchestration' },
    state: clone(STATES.find(x => x.name === state)), labels: [clone(LABELS.find(x => x.name === laneName))],
    relations: [], teamStates: clone(STATES), teamLabels: clone(LABELS),
  };
}

class FakeAuthority {
  constructor(items) { this.items = new Map(items.map(x => [x.identifier, clone(x)])); this.rev = 1; this.failNext = false; this.ambiguousAfterNext = false; this.commentBeforeNextTransition = false; this.materialBeforeNextTransition = null; this.commentWrites = 0; this.history = []; }
  async getIssue(ref) { const v = this.items.get(ref); if (!v) { const e = new Error('missing'); e.code = 'WORK_NOT_FOUND'; throw e; } return clone(v); }
  async transition({ issue: base, expectedRevision, expectedState, expectedLane, targetState, targetLane, description = null }) {
    if (this.failNext) { this.failNext = false; const e = new Error('forced'); e.code = 'LINEAR_UPSTREAM_GRAPHQL'; throw e; }
    const current = this.items.get(base.identifier);
    if (this.commentBeforeNextTransition) { this.commentBeforeNextTransition = false; this.commentWrites += 1; current.updatedAt = `rev-${++this.rev}`; }
    if (this.materialBeforeNextTransition) { const patch = this.materialBeforeNextTransition; this.materialBeforeNextTransition = null; this.humanEdit(base.identifier, patch); }
    if (semantic(current) !== semantic(base) || current.state.name !== expectedState || lane(current)?.name !== expectedLane) {
      const e = new Error('changed'); e.code = 'WORK_STATE_CHANGED'; e.details = { actual_state: current.state.name, actual_lane: lane(current)?.name, expected_revision: expectedRevision, actual_revision: current.updatedAt }; throw e;
    }
    current.state = clone(STATES.find(x => x.name === targetState));
    current.labels = [...current.labels.filter(x => !x.name.startsWith('lane:')), clone(LABELS.find(x => x.name === targetLane))];
    if (description !== null) current.description = description;
    current.updatedAt = `rev-${++this.rev}`;
    this.history.push({ ref: current.identifier, state: targetState, lane: targetLane });
    if (this.ambiguousAfterNext) { this.ambiguousAfterNext = false; const e = new Error('ambiguous after mutation'); e.code = 'LINEAR_UPSTREAM_HTTP'; throw e; }
    return clone(current);
  }
  humanEdit(ref, patch = {}) {
    const current = this.items.get(ref);
    if (patch.state) current.state = clone(STATES.find(x => x.name === patch.state));
    if (patch.lane) current.labels = [clone(LABELS.find(x => x.name === patch.lane))];
    if (patch.description) current.description = patch.description;
    if (patch.priority !== undefined) current.priority = patch.priority;
    current.updatedAt = `rev-${++this.rev}`;
  }
  addComment(ref) {
    const current = this.items.get(ref);
    this.commentWrites += 1;
    current.updatedAt = `rev-${++this.rev}`;
  }
  appendExecutionEvidence(ref, text = 'Execution evidence: verified head abc123') {
    const current = this.items.get(ref);
    current.description = `${current.description}\n\n${text}`;
    current.updatedAt = `rev-${++this.rev}`;
  }
  addMetadataLabel(ref, name = 'bookkeeping:evidence-recorded') {
    const current = this.items.get(ref);
    current.labels.push({ id: `meta-${name}`, name });
    current.updatedAt = `rev-${++this.rev}`;
  }
}

class MemoryStore {
  constructor() { this.leases = new Map(); this.claims = new Map(); this.tokens = new Map(); this.slots = new Map(); this.checkpoints = new Map(); this.heartbeats = new Map(); }
  slotKey(w,g) { return `${w}|${g}`; }
  checkpointKey(leaseId,k) { return `${leaseId}|${k}`; }
  async getClaimByIdempotency(k) { return this.claims.get(k) || null; }
  async getLeaseById(id) { return this.leases.get(id) || null; }
  async getLeaseByTokenHash(h) { return this.tokens.get(h) || null; }
  async getSlot(w,g) { return this.slots.get(this.slotKey(w,g)) || null; }
  async getCheckpointByIdempotency(leaseId,k) { return this.checkpoints.get(this.checkpointKey(leaseId,k)) || null; }
  async getLatestCheckpoint(leaseId) { return [...this.checkpoints.values()].filter(x=>x.lease_id===leaseId).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at)))[0] || null; }
  async getHeartbeatByIdempotency(leaseId,k) { return this.heartbeats.get(`${leaseId}|${k}`) || null; }
  async listRecentHeartbeats(leaseId,limit=2) { return [...this.heartbeats.values()].filter(x=>x.lease_id===leaseId).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).slice(0,limit); }
  async listContinuationCandidates(workRef,gate) { return [...this.leases.values()].filter(l=>l.work_ref===workRef&&((l.status==='settled'&&l.settle_plan?.lane===gate&&l.settle_plan?.continuation)||(l.status==='expired'&&l.gate===gate&&l.reconciliation?.restored===true))).sort((a,b)=>String(b.settled_at||b.updated_at||b.created_at).localeCompare(String(a.settled_at||a.updated_at||a.created_at))); }
  async insertCheckpoint(leaseId,idem,requestHash,checkpoint,checkpointSha,createdAt) { const k=this.checkpointKey(leaseId,idem); const prior=this.checkpoints.get(k); if(prior){if(prior.request_sha256!==requestHash){const e=new Error('conflict');e.code='IDEMPOTENCY_CONFLICT';throw e;}return prior;} const row={lease_id:leaseId,idempotency_key:idem,request_sha256:requestHash,checkpoint:clone(checkpoint),checkpoint_sha256:checkpointSha,created_at:createdAt}; this.checkpoints.set(k,row); return row; }
  async insertLease(l) { if (this.claims.has(l.claim_idempotency_key)) return { inserted:false, lease:this.claims.get(l.claim_idempotency_key) }; const v={...clone(l)}; this.leases.set(v.lease_id,v); this.claims.set(v.claim_idempotency_key,v); this.tokens.set(v.token_hash,v); return {inserted:true,lease:v}; }
  async tryAcquireSlot(w,g,id,expires) { const k=this.slotKey(w,g); if(this.slots.has(k)) return false; this.slots.set(k,{work_ref:w,gate:g,lease_id:id,expires_at:expires}); return true; }
  async activateLease(id,rev,receipt) { const l=this.leases.get(id); l.status='active'; l.active_revision=rev; l.claim_receipt=clone(receipt); return l; }
  async extendLeaseWithHeartbeat(input) { const l=this.leases.get(input.lease_id); const s=this.slots.get(this.slotKey(input.work_ref,input.gate)); if(!l||l.status!=='active'||!s||s.lease_id!==input.lease_id){const e=new Error('expired');e.code='LEASE_EXPIRED';throw e;} l.expires_at=input.new_expires_at;l.last_heartbeat_at=input.created_at;l.heartbeat_count=(l.heartbeat_count||0)+1;s.expires_at=input.new_expires_at;const row={...clone(input),heartbeat_count:l.heartbeat_count};this.heartbeats.set(`${input.lease_id}|${input.idempotency_key}`,row);return row; }
  async rejectLease(id,code,details) { const l=this.leases.get(id); l.status='rejected'; l.rejection_code=code; l.rejection_details=clone(details); return l; }
  async markExpired(id,recon) { const l=this.leases.get(id); if(l.status!=='settled') l.status='expired'; l.reconciliation=clone(recon); return l; }
  async invalidateLease(id,recon) { const l=this.leases.get(id); if(l.status!=='settled') l.status='invalidated'; l.reconciliation=clone(recon); return l; }
  async releaseSlot(w,g,id) { const k=this.slotKey(w,g); const s=this.slots.get(k); if(s?.lease_id===id){this.slots.delete(k);return 1;} return 0; }
  async beginSettlement(id,idem,hash,plan) { const l=this.leases.get(id); if(l.status==='active'&&!l.settle_idempotency_key){l.status='settling';l.settle_idempotency_key=idem;l.settle_request_hash=hash;l.settle_plan=clone(plan);return l;} if(l.settle_idempotency_key===idem&&l.settle_request_hash===hash)return l; const e=new Error('consumed');e.code='LEASE_ALREADY_SETTLED';throw e; }
  async completeSettlement(id,idem,hash,plan,receipt,settledAt) { const l=this.leases.get(id); l.status='settled';l.settle_idempotency_key=idem;l.settle_request_hash=hash;l.settle_plan=clone(plan);l.settle_receipt=clone(receipt);l.settled_at=settledAt;return l; }
}

function harness({ state='Todo', laneName='lane:repo-implementation', ref='LJH-T1' }={}) {
  let ms = Date.parse('2026-08-16T20:00:00Z'); let token = 0;
  const authority = new FakeAuthority([issue(ref,state,laneName)]); const store = new MemoryStore();
  const service = createWorkLeaseService({store,authoritative:authority,now:()=>new Date(ms).toISOString(),tokenFactory:()=>`test-token-${++token}`});
  return {service,store,authority,advance:s=>{ms+=s*1000;},ref};
}
function claimReq(ref='LJH-T1', idem='claim-1', extra={}) { return {work_ref:ref,run_id:'test-run',expected_state:'Todo',expected_lane:'lane:repo-implementation',lease_seconds:1800,idempotency_key:idem,...extra}; }
function settleReq(token, disposition='requeue', idem='settle-1', extra={}) { return {lease_token:token,disposition,idempotency_key:idem,evidence:[],...extra}; }
async function expectCode(fn, code) { try { await fn(); } catch(e) { if(e.code===code) return e; throw new Error(`expected ${code}, got ${e.code}: ${e.message}`); } throw new Error(`expected ${code}, got success`); }
function assert(v,msg){ if(!v) throw new Error(msg); }

export async function runWorkLeaseTests() {
  const tests=[]; async function test(name,fn){try{await fn();tests.push({name,ok:true});}catch(e){tests.push({name,ok:false,error:String(e.message||e)});}}

  await test('1 successful claim of executable Todo', async()=>{const h=harness();const r=await h.service.claim(claimReq());assert(r.ok&&r.previous_state==='Todo','claim failed');});
  await test('2 active lifecycle transition during claim', async()=>{const h=harness();await h.service.claim(claimReq());assert((await h.authority.getIssue(h.ref)).state.name==='In Progress','not active');});
  await test('3 second claimant rejected while lease active', async()=>{const h=harness();await h.service.claim(claimReq());await expectCode(()=>h.service.claim(claimReq(h.ref,'claim-2')), 'ALREADY_CLAIMED');});
  await test('4 expired lease can be reclaimed from truthfully observed In Progress', async()=>{const h=harness();await h.service.claim(claimReq());h.advance(1801);const r=await h.service.claim(claimReq(h.ref,'claim-2',{expected_state:'In Progress'}));assert(r.ok&&r.lease_id,'reclaim failed');});
  await test('5 stale lease cannot settle after successor claim', async()=>{const h=harness();const a=await h.service.claim(claimReq());h.advance(1801);await h.service.claim(claimReq(h.ref,'claim-2',{expected_state:'In Progress'}));await expectCode(()=>h.service.settle(settleReq(a.lease_token)), 'LEASE_EXPIRED');});
  await test('6 claim idempotent replay', async()=>{const h=harness();const a=await h.service.claim(claimReq());const b=await h.service.claim(claimReq());assert(a.lease_id===b.lease_id&&a.lease_token===b.lease_token&&b.idempotent_replay,'not replayed');});
  await test('7 state precondition mismatch', async()=>{const h=harness();await expectCode(()=>h.service.claim(claimReq(h.ref,'c',{expected_state:'Backlog'})),'STATE_MISMATCH');});
  await test('8 lane precondition mismatch', async()=>{const h=harness();await expectCode(()=>h.service.claim(claimReq(h.ref,'c',{expected_lane:'lane:verification'})),'LANE_MISMATCH');});
  await test('9 Linear transition failure means claim does not report success', async()=>{const h=harness();h.authority.failNext=true;await expectCode(()=>h.service.claim(claimReq()),'LINEAR_TRANSITION_FAILED');assert(!(await h.store.getSlot(h.ref,'lane:repo-implementation')),'slot stranded');});
  await test('10 completed settlement', async()=>{const h=harness();const a=await h.service.claim(claimReq());const r=await h.service.settle(settleReq(a.lease_token,'completed'));assert(r.current_state==='Todo'&&r.current_lane==='lane:verification','wrong successor');});
  await test('11 requeue settlement', async()=>{const h=harness();const a=await h.service.claim(claimReq());const r=await h.service.settle(settleReq(a.lease_token));assert(r.current_state==='Todo'&&r.current_lane==='lane:repo-implementation','wrong requeue');});
  await test('12 blocked settlement', async()=>{const h=harness();const a=await h.service.claim(claimReq());const r=await h.service.settle(settleReq(a.lease_token,'blocked','s',{reason:'Durable upstream source unavailable',promotion_condition:'Authoritative source becomes retrievable'}));const i=await h.authority.getIssue(h.ref);assert(r.current_state==='Backlog'&&i.description.includes('Execution blocker'),'block not recorded');});
  await test('13 settlement idempotent replay', async()=>{const h=harness();const a=await h.service.claim(claimReq());const x=await h.service.settle(settleReq(a.lease_token));const y=await h.service.settle(settleReq(a.lease_token));assert(x.lease_id===y.lease_id&&y.idempotent_replay,'settle replay failed');});
  await test('14 settlement with expired token rejected', async()=>{const h=harness();const a=await h.service.claim(claimReq());h.advance(1801);await expectCode(()=>h.service.settle(settleReq(a.lease_token)),'LEASE_EXPIRED');});
  await test('15 consumed token rejects different settlement identity', async()=>{const h=harness();const a=await h.service.claim(claimReq());await h.service.settle(settleReq(a.lease_token));await expectCode(()=>h.service.settle(settleReq(a.lease_token,'requeue','settle-2')),'LEASE_ALREADY_SETTLED');});
  await test('16 managed execution contract changed after claim', async()=>{const h=harness();const a=await h.service.claim(claimReq());const i=await h.authority.getIssue(h.ref);h.authority.humanEdit(h.ref,{description:i.description.replace('Acceptance: deterministic','Acceptance: materially changed')});await expectCode(()=>h.service.settle(settleReq(a.lease_token)),'WORK_STATE_CHANGED');});
  await test('17 human lifecycle change after claim is not overwritten', async()=>{const h=harness();const a=await h.service.claim(claimReq());h.authority.humanEdit(h.ref,{state:'Done'});await expectCode(()=>h.service.settle(settleReq(a.lease_token)),'WORK_STATE_CHANGED');assert((await h.authority.getIssue(h.ref)).state.name==='Done','human change overwritten');});
  await test('18 stale In Progress recovery after crashed worker', async()=>{const h=harness();await h.service.claim(claimReq());h.advance(1801);await h.service.claim(claimReq(h.ref,'claim-2',{expected_state:'In Progress'}));const seq=h.authority.history.map(x=>x.state).join('>');assert(seq.includes('In Progress>Todo>In Progress'),`bad recovery ${seq}`);});
  await test('19 concurrent claim race permits exactly one winner', async()=>{const h=harness();const results=await Promise.allSettled([h.service.claim(claimReq(h.ref,'race-a')),h.service.claim(claimReq(h.ref,'race-b'))]);assert(results.filter(x=>x.status==='fulfilled').length===1,'race had wrong winners');});
  await test('20 no claim/comment marker writes are needed in Linear', async()=>{const h=harness();const a=await h.service.claim(claimReq());await h.service.settle(settleReq(a.lease_token));assert(h.authority.commentWrites===0,'comment marker written');});
  await test('21 completed verification may route to validated remediation lane', async()=>{const h=harness({laneName:'lane:verification'});const a=await h.service.claim(claimReq(h.ref,'claim-v',{expected_lane:'lane:verification'}));const r=await h.service.settle(settleReq(a.lease_token,'completed','settle-v',{next_state:'Todo',next_lane:'lane:repo-implementation'}));assert(r.current_state==='Todo'&&r.current_lane==='lane:repo-implementation','verification remediation route failed');});
  await test('22 invalid completed successor is rejected', async()=>{const h=harness();const a=await h.service.claim(claimReq());await expectCode(()=>h.service.settle(settleReq(a.lease_token,'completed','settle-bad',{next_state:'Done',next_lane:'lane:integration'})),'INVALID_SUCCESSOR');});
  await test('23 ambiguous claim transition recovers only by exact idempotent replay', async()=>{const h=harness();h.authority.ambiguousAfterNext=true;await expectCode(()=>h.service.claim(claimReq()),'CLAIM_INDETERMINATE');const r=await h.service.claim(claimReq());assert(r.ok&&r.idempotent_replay&&r.current_state==='In Progress','ambiguous claim did not recover');assert(h.authority.history.length===1,'claim transition repeated');});
  await test('24 settlement receipt retains bounded evidence refs', async()=>{const h=harness();const a=await h.service.claim(claimReq());await h.service.settle(settleReq(a.lease_token,'requeue','settle-evidence',{evidence:[{kind:'git_head',ref:'abc123'}]}));const l=await h.store.getLeaseById(a.lease_id);assert(l.settle_plan.evidence?.[0]?.ref==='abc123','evidence ref not retained');});
  await test('25 stale recovery rejects a precondition that was not actually observed', async()=>{const h=harness();await h.service.claim(claimReq());h.advance(1801);await expectCode(()=>h.service.claim(claimReq(h.ref,'claim-wrong',{expected_state:'Todo'})),'STATE_MISMATCH');assert((await h.authority.getIssue(h.ref)).state.name==='In Progress','mismatched probe mutated authoritative state');const r=await h.service.claim(claimReq(h.ref,'claim-correct',{expected_state:'In Progress'}));assert(r.ok&&r.previous_state==='Todo','truthful recovery precondition did not reclaim');});
  await test('26 orphaned In Progress without a lease is recovered and claimed', async()=>{const h=harness({state:'In Progress'});const r=await h.service.claim(claimReq(h.ref,'orphan-claim',{expected_state:'In Progress'}));assert(r.ok&&r.previous_state==='Todo'&&r.current_state==='In Progress','orphan recovery failed');const seq=h.authority.history.map(x=>x.state).join('>');assert(seq==='Todo>In Progress',`bad orphan recovery ${seq}`);});
  await test('27 orphan recovery preserves optimistic state fencing', async()=>{const h=harness({state:'In Progress'});await expectCode(()=>h.service.claim(claimReq(h.ref,'orphan-wrong',{expected_state:'Todo'})),'STATE_MISMATCH');assert((await h.authority.getIssue(h.ref)).state.name==='In Progress','wrong precondition mutated orphan');});
  await test('28 expired slot with missing lease record recovers safely', async()=>{const h=harness({state:'In Progress'});h.store.slots.set(`${h.ref}|lane:repo-implementation`,{work_ref:h.ref,gate:'lane:repo-implementation',lease_id:'missing-lease',expires_at:'2026-08-16T19:00:00.000Z'});const r=await h.service.claim(claimReq(h.ref,'missing-lease-recovery',{expected_state:'In Progress'}));assert(r.ok&&r.previous_state==='Todo'&&r.current_state==='In Progress','missing-lease recovery failed');assert((await h.store.getSlot(h.ref,'lane:repo-implementation'))?.lease_id===r.lease_id,'successor slot not authoritative');});
  await test('29 Linear comment revision after claim does not invalidate settlement', async()=>{const h=harness();const a=await h.service.claim(claimReq());h.authority.addComment(h.ref);const r=await h.service.settle(settleReq(a.lease_token,'completed','comment-safe-settle'));assert(r.current_lane==='lane:verification','comment-only revision blocked settlement');});
  await test('30 Linear comment arriving during settlement transition is tolerated', async()=>{const h=harness();const a=await h.service.claim(claimReq());h.authority.commentBeforeNextTransition=true;const r=await h.service.settle(settleReq(a.lease_token,'completed','comment-race-settle'));assert(r.current_lane==='lane:verification'&&h.authority.commentWrites===1,'comment race blocked transition');});
  await test('31 priority edit after claim still invalidates settlement', async()=>{const h=harness();const a=await h.service.claim(claimReq());h.authority.humanEdit(h.ref,{priority:1});await expectCode(()=>h.service.settle(settleReq(a.lease_token,'completed','priority-edit-settle')),'WORK_STATE_CHANGED');});
  await test('32 comment-only revision does not prevent expired lease recovery', async()=>{const h=harness();await h.service.claim(claimReq());h.authority.addComment(h.ref);h.advance(1801);const r=await h.service.claim(claimReq(h.ref,'comment-recovery',{expected_state:'In Progress'}));assert(r.ok&&r.current_state==='In Progress','comment-only revision stranded expired lease');});
  await test('33 pre-upgrade claim snapshots remain settle-compatible', async()=>{const h=harness();const a=await h.service.claim(claimReq());const lease=await h.store.getLeaseById(a.lease_id);delete lease.claim_receipt.execution_projection;delete lease.claim_receipt.execution_fingerprint;h.authority.addComment(h.ref);const r=await h.service.settle(settleReq(a.lease_token,'completed','legacy-snapshot-settle'));assert(r.current_lane==='lane:verification','legacy snapshot was invalidated by comment revision');});
  await test('34 completion evidence appended after claim does not strand settlement', async()=>{const h=harness();const a=await h.service.claim(claimReq());const claimRev=a.authoritative_revision;h.authority.appendExecutionEvidence(h.ref);const before=await h.authority.getIssue(h.ref);assert(before.updatedAt!==claimRev,'evidence did not advance broad revision');const r=await h.service.settle(settleReq(a.lease_token,'completed','evidence-safe-settle'));assert(r.current_lane==='lane:verification','completion evidence blocked settlement');assert(r.claim_authoritative_revision===claimRev,'claim revision evidence missing');assert(r.execution_precondition_verified===true,'semantic precondition not recorded');});
  await test('35 unrelated metadata label after claim does not strand settlement', async()=>{const h=harness();const a=await h.service.claim(claimReq());h.authority.addMetadataLabel(h.ref);const r=await h.service.settle(settleReq(a.lease_token,'completed','metadata-safe-settle'));assert(r.current_lane==='lane:verification','metadata label blocked settlement');});
  await test('36 source authority change remains material settlement rejection', async()=>{const h=harness();const a=await h.service.claim(claimReq());const i=await h.authority.getIssue(h.ref);h.authority.humanEdit(h.ref,{description:i.description.replace('Authority: GitHub #1','Authority: GitHub #2')});const e=await expectCode(()=>h.service.settle(settleReq(a.lease_token,'completed','authority-change-settle')),'WORK_STATE_CHANGED');assert(e.details?.changed_fields?.includes('authority'),'authority mismatch not explained');const lease=await h.store.getLeaseById(a.lease_id);assert(lease.status==='invalidated','rejected settlement left lease owning');assert(!(await h.store.getSlot(h.ref,'lane:repo-implementation')),'rejected settlement left active slot');});
  await test('37 material lane race during settlement terminates lease instead of stranding settling', async()=>{const h=harness();const a=await h.service.claim(claimReq());h.authority.materialBeforeNextTransition={lane:'lane:verification'};await expectCode(()=>h.service.settle(settleReq(a.lease_token,'completed','lane-race-settle')),'WORK_STATE_CHANGED');const lease=await h.store.getLeaseById(a.lease_id);assert(lease.status==='invalidated','transition-time rejection left lease settling');assert(!(await h.store.getSlot(h.ref,'lane:repo-implementation')),'transition-time rejection left slot active');});
  await test('38 upstream failure before settlement mutation preserves retryable settling state', async()=>{const h=harness();const a=await h.service.claim(claimReq());h.authority.failNext=true;await expectCode(()=>h.service.settle(settleReq(a.lease_token,'completed','settle-retry')),'LINEAR_UPSTREAM_GRAPHQL');const mid=await h.store.getLeaseById(a.lease_id);assert(mid.status==='settling','indeterminate pre-mutation failure released ownership');const r=await h.service.settle(settleReq(a.lease_token,'completed','settle-retry'));assert(r.current_lane==='lane:verification','retry did not resolve settlement');});
  await test('39 ambiguous failure after settlement mutation resolves by idempotent reread', async()=>{const h=harness();const a=await h.service.claim(claimReq());h.authority.ambiguousAfterNext=true;await expectCode(()=>h.service.settle(settleReq(a.lease_token,'completed','settle-ambiguous')),'LINEAR_UPSTREAM_HTTP');const transitions=h.authority.history.length;const r=await h.service.settle(settleReq(a.lease_token,'completed','settle-ambiguous'));assert(r.idempotent_replay&&r.current_lane==='lane:verification','ambiguous mutation did not reconcile');assert(h.authority.history.length===transitions,'retry repeated lifecycle transition');});
  await test('40 new claims persist deterministic execution projection evidence', async()=>{const h=harness();const a=await h.service.claim(claimReq());const lease=await h.store.getLeaseById(a.lease_id);assert(lease.claim_receipt.execution_projection?.work_ref===h.ref,'execution projection not persisted');assert(typeof lease.claim_receipt.execution_fingerprint==='string'&&lease.claim_receipt.execution_fingerprint.length===64,'execution fingerprint not persisted');});
  await test('41 bold Markdown managed fields normalize into execution projection', async()=>{const h=harness();h.authority.humanEdit(h.ref,{description:'**Repository:** `owner/repo`\n\n**Authority:** GitHub #1\n\n**Objective:**\nKeep exact source identity.\n\n**Gate:**\nImplement bounded work.\n\n**Acceptance:**\n- deterministic\n- source-backed'});const a=await h.service.claim(claimReq(h.ref,'bold-fields-claim'));const lease=await h.store.getLeaseById(a.lease_id);const p=lease.claim_receipt.execution_projection;assert(p.repository==='`owner/repo`','bold repository not normalized');assert(p.authority==='GitHub #1','bold authority not normalized');assert(p.objective==='Keep exact source identity.','bold objective not normalized');assert(p.gate==='Implement bounded work.','bold gate not normalized');assert(p.acceptance.length===2&&p.acceptance[0]==='deterministic','bold acceptance not normalized');});
  await test('42 completed settlement hands exact candidate continuation to successor claim', async()=>{const h=harness({laneName:'lane:source-implementation'});const a=await h.service.claim(claimReq(h.ref,'source-c1',{expected_lane:'lane:source-implementation'}));await h.service.settle(settleReq(a.lease_token,'completed','source-s1',{continuation:{schema:'work-continuation-v1',candidate:{kind:'github_pull_request',repository:'owner/repo',pull_request:186,head_sha:'998448d744f4055a4a3e45ed78e3bfc67cbf546e'},checkpoint:{phase:'candidate_ready',next_action_kind:'verify_candidate',completed:[],evidence:[]},evidence:[{kind:'github_pull_request',ref:'owner/repo#186'},{kind:'git_head',ref:'998448d744f4055a4a3e45ed78e3bfc67cbf546e'}]}}));const b=await h.service.claim(claimReq(h.ref,'verify-c1',{expected_lane:'lane:verification'}));assert(b.continuation?.packet?.candidate?.head_sha==='998448d744f4055a4a3e45ed78e3bfc67cbf546e','successor lost exact candidate head');assert(b.continuation?.from_gate==='lane:source-implementation','predecessor gate missing');});
  await test('43 checkpoint survives graceful same-lane requeue', async()=>{const h=harness({laneName:'lane:source-implementation'});const a=await h.service.claim(claimReq(h.ref,'source-cp1',{expected_lane:'lane:source-implementation'}));const cp=await h.service.checkpoint({lease_token:a.lease_token,idempotency_key:'checkpoint-1',checkpoint:{phase:'diagnostic_complete',next_action_kind:'apply_repository_change',completed:[{kind:'diagnostic',ref:'defaults.unincorporated.status'}],evidence:[{kind:'source_coordinate',ref:'US-ME'}]}});assert(cp.ok&&cp.checkpoint_sha256,'checkpoint not persisted');await h.service.settle(settleReq(a.lease_token,'requeue','source-rq1',{requeue_class:'resume_progress'}));const b=await h.service.claim(claimReq(h.ref,'source-cp2',{expected_lane:'lane:source-implementation'}));assert(b.continuation?.packet?.checkpoint?.next_action_kind==='apply_repository_change','same-lane checkpoint not resumed');});
  await test('44 checkpoint survives expired-lease recovery without stale ownership', async()=>{const h=harness({laneName:'lane:source-implementation'});const a=await h.service.claim(claimReq(h.ref,'source-exp1',{expected_lane:'lane:source-implementation'}));await h.service.checkpoint({lease_token:a.lease_token,idempotency_key:'checkpoint-exp',checkpoint:{phase:'research_partial',next_action_kind:'continue_research',completed:[{kind:'primary_source',ref:'Halifax permit by-law'}],evidence:[{kind:'source_coordinate',ref:'CA-NS'}]}});h.advance(1801);const b=await h.service.claim(claimReq(h.ref,'source-exp2',{expected_state:'In Progress',expected_lane:'lane:source-implementation'}));assert(b.continuation?.recovered_from_expired_lease===true,'expired continuation not marked recovered');assert(b.continuation?.packet?.checkpoint?.phase==='research_partial','expired checkpoint was lost');});
  await test('45 resume_progress requeue refuses to discard progress without checkpoint', async()=>{const h=harness({laneName:'lane:source-implementation'});const a=await h.service.claim(claimReq(h.ref,'source-no-cp',{expected_lane:'lane:source-implementation'}));await expectCode(()=>h.service.settle(settleReq(a.lease_token,'requeue','source-no-cp-rq',{requeue_class:'resume_progress'})),'CHECKPOINT_REQUIRED');});
  await test('46 material Linear execution edit invalidates stale predecessor continuation', async()=>{const h=harness({laneName:'lane:source-implementation'});const a=await h.service.claim(claimReq(h.ref,'source-material-c1',{expected_lane:'lane:source-implementation'}));await h.service.settle(settleReq(a.lease_token,'completed','source-material-s1',{continuation:{schema:'work-continuation-v1',candidate:{kind:'github_pull_request',repository:'owner/repo',pull_request:186,head_sha:'998448d744f4055a4a3e45ed78e3bfc67cbf546e'},checkpoint:{phase:'candidate_ready',next_action_kind:'verify_candidate',completed:[],evidence:[]},evidence:[{kind:'git_head',ref:'998448d744f4055a4a3e45ed78e3bfc67cbf546e'}]}}));h.authority.humanEdit(h.ref,{priority:1});const b=await h.service.claim(claimReq(h.ref,'verify-material-c1',{expected_lane:'lane:verification'}));assert(b.continuation===null,'stale continuation survived material execution edit');});
  await test('47 checkpoint idempotency conflicts on changed payload', async()=>{const h=harness({laneName:'lane:source-implementation'});const a=await h.service.claim(claimReq(h.ref,'source-idem-c1',{expected_lane:'lane:source-implementation'}));const first={lease_token:a.lease_token,idempotency_key:'checkpoint-idem',checkpoint:{phase:'research_partial',next_action_kind:'continue_research',completed:[],evidence:[]}};const x=await h.service.checkpoint(first);const y=await h.service.checkpoint(first);assert(x.checkpoint_sha256===y.checkpoint_sha256&&y.idempotent_replay===true,'checkpoint replay failed');await expectCode(()=>h.service.checkpoint({...first,checkpoint:{...first.checkpoint,phase:'different'}}),'IDEMPOTENCY_CONFLICT');});
  await test('48 heartbeat extends active lease and slot from durable progress', async()=>{const h=harness();const a=await h.service.claim(claimReq());h.advance(1200);const r=await h.service.heartbeat({lease_token:a.lease_token,run_id:'test-run',extend_seconds:1800,idempotency_key:'hb-1',checkpoint:{phase:'implementation_progress',next_action_kind:'apply_repository_change',completed:[{kind:'git_head',ref:'abc'}],evidence:[]}});assert(Date.parse(r.expires_at)>Date.parse(a.expires_at),'heartbeat did not extend expiry');const slot=await h.store.getSlot(h.ref,'lane:repo-implementation');assert(slot.expires_at===r.expires_at,'slot expiry diverged from lease');});
  await test('49 expired lease cannot heartbeat', async()=>{const h=harness();const a=await h.service.claim(claimReq());h.advance(1801);await expectCode(()=>h.service.heartbeat({lease_token:a.lease_token,run_id:'test-run',extend_seconds:1800,idempotency_key:'hb-exp',checkpoint:{phase:'late',next_action_kind:'apply_repository_change',completed:[],evidence:[]}}),'LEASE_EXPIRED');});
  await test('50 heartbeat fails closed on material execution-state change', async()=>{const h=harness();const a=await h.service.claim(claimReq());h.authority.humanEdit(h.ref,{priority:1});await expectCode(()=>h.service.heartbeat({lease_token:a.lease_token,run_id:'test-run',extend_seconds:1800,idempotency_key:'hb-material',checkpoint:{phase:'changed',next_action_kind:'apply_repository_change',completed:[],evidence:[]}}),'WORK_STATE_CHANGED');assert(!(await h.store.getSlot(h.ref,'lane:repo-implementation')),'invalid heartbeat retained slot ownership');});
  await test('51 heartbeat requires a durable progress checkpoint', async()=>{const h=harness();const a=await h.service.claim(claimReq());h.advance(1200);await expectCode(()=>h.service.heartbeat({lease_token:a.lease_token,run_id:'test-run',extend_seconds:1800,idempotency_key:'hb-no-progress'}),'CHECKPOINT_REQUIRED');});
  await test('52 registered run budget caps claim and rejects a new gate inside reserve', async()=>{const h=harness();h.store.getRunBudget=async()=>({deadline_at:'2026-08-16T20:45:00.000Z',settlement_reserve_seconds:300,minimum_new_gate_seconds:600});const a=await h.service.claim(claimReq());assert(a.expires_at==='2026-08-16T20:30:00.000Z','initial claim unexpectedly changed before cap applies');await h.service.settle(settleReq(a.lease_token));h.advance(2101);await expectCode(()=>h.service.claim(claimReq(h.ref,'budget-late')),'RUN_BUDGET_EXHAUSTED');});
  await test('53 heartbeat is idempotent and refuses repeated no-progress lease reservation', async()=>{const h=harness();const a=await h.service.claim(claimReq());h.advance(1200);const request={lease_token:a.lease_token,run_id:'test-run',extend_seconds:1800,idempotency_key:'hb-idem',checkpoint:{phase:'same-progress',next_action_kind:'apply_repository_change',completed:[{kind:'git_head',ref:'abc'}],evidence:[]}};const x=await h.service.heartbeat(request);const y=await h.service.heartbeat(request);assert(x.expires_at===y.expires_at&&y.idempotent_replay===true,'heartbeat replay was not idempotent');h.advance(600);await h.service.heartbeat({...request,idempotency_key:'hb-same-2'});h.advance(600);await expectCode(()=>h.service.heartbeat({...request,idempotency_key:'hb-same-3'}),'NO_PROGRESS_HEARTBEAT');});
  await test('54 registered run scope fences claims to declared lane and repository', async()=>{const h=harness();h.store.getRunBudget=async()=>({status:'active',deadline_at:'2026-08-16T20:45:00.000Z',settlement_reserve_seconds:300,minimum_new_gate_seconds:600,scope:{project:'Portfolio Orchestration',lanes:['lane:verification'],repositories:[]}});await expectCode(()=>h.service.claim(claimReq()),'RUN_SCOPE_VIOLATION');});
  await test('55 production run-aware store rejects unregistered run ids', async()=>{const h=harness();h.store.getRunBudget=async()=>null;await expectCode(()=>h.service.claim(claimReq()),'RUN_NOT_REGISTERED');});
  await test('56 Postgres heartbeat persistence uses one explicit transaction instead of a data-modifying CTE query', async()=>{const queries=[];let transactions=0;let ops=[];const fakeDb={async query(text){queries.push(text);return {rows:[]};},async transaction(items){transactions+=1;ops=items;return {results:items.map(()=>({rows:[],rowCount:0}))};}};const store=createPostgresLeaseStore(fakeDb);await expectCode(()=>store.extendLeaseWithHeartbeat({lease_id:'00000000-0000-4000-8000-000000000001',work_ref:'LJH-T1',gate:'lane:repo-implementation',idempotency_key:'hb-atomic',request_sha256:'a'.repeat(64),progress_sha256:'b'.repeat(64),previous_expires_at:'2026-08-16T20:30:00.000Z',new_expires_at:'2026-08-16T20:40:00.000Z',created_at:'2026-08-16T20:10:00.000Z'}),'LEASE_EXPIRED');assert(transactions===1&&ops.length>=4,'heartbeat persistence did not use one explicit database transaction');assert(!queries.some(sql=>/WITH\s+heartbeat_reservation/i.test(sql)),'heartbeat persistence still used unsupported data-modifying CTE db.query');});
  await test('57 run scope is checked before stale lease reconciliation can mutate Linear', async()=>{const h=harness();h.store.getRunBudget=async()=>({status:'active',deadline_at:'2026-08-16T21:00:00.000Z',settlement_reserve_seconds:300,minimum_new_gate_seconds:600,scope:{project:'Portfolio Orchestration',lanes:['lane:repo-implementation'],repositories:[]}});await h.service.claim(claimReq());h.advance(1801);h.store.getRunBudget=async()=>({status:'active',deadline_at:'2026-08-16T21:00:00.000Z',settlement_reserve_seconds:300,minimum_new_gate_seconds:600,scope:{project:'Portfolio Orchestration',lanes:['lane:verification'],repositories:[]}});await expectCode(()=>h.service.claim(claimReq(h.ref,'claim-scope-stale',{expected_state:'In Progress'})),'RUN_SCOPE_VIOLATION');assert((await h.authority.getIssue(h.ref)).state.name==='In Progress','out-of-scope claim mutated authoritative lifecycle during reconciliation');});
  await test('58 heartbeat cannot outlive a missing registered run record', async()=>{const h=harness();h.store.getRunBudget=async()=>({status:'active',deadline_at:'2026-08-16T21:00:00.000Z',settlement_reserve_seconds:300,minimum_new_gate_seconds:600,scope:{project:'Portfolio Orchestration',lanes:['lane:repo-implementation'],repositories:[]}});const a=await h.service.claim(claimReq());h.advance(1200);h.store.getRunBudget=async()=>null;await expectCode(()=>h.service.heartbeat({lease_token:a.lease_token,run_id:'test-run',extend_seconds:1800,idempotency_key:'hb-no-run',checkpoint:{phase:'progress',next_action_kind:'apply_repository_change',completed:[{kind:'git_head',ref:'abc'}],evidence:[]}}),'RUN_NOT_REGISTERED');});

  return {ok:tests.every(t=>t.ok),passed:tests.filter(t=>t.ok).length,failed:tests.filter(t=>!t.ok).length,tests};
}