import assert from 'node:assert/strict';
import test from 'node:test';
import { createCloudRunHandler } from './cloud-run-host.mjs';
import { createPostgresSemanticCommandReceiptStore } from '../lib/semantic-command-receipts.js';

const SOURCE='a'.repeat(40);
function responseRecorder(){return{statusCode:null,headers:null,body:'',writeHead(statusCode,headers){this.statusCode=statusCode;this.headers=headers;},end(body=''){this.body+=body;}};}
async function request({method='POST',url='/api/worker-command',body='{}',headers={}}={}){return{method,url,headers,async *[Symbol.asyncIterator](){if(body)yield Buffer.from(body);}};}
function memoryDb(){const rows=new Map();return{rows,async query(sql,params=[]){if(sql==='SELECT 1 AS ok')return{rows:[{ok:1}]};if(sql.includes('INSERT INTO semantic_command_receipts')){const [requestId,receiptRef,command,sourceRevision,requestSha,responseSha,receiptSha,receiptJson]=params;if(rows.has(requestId))return{rows:[]};const receipt=JSON.parse(receiptJson);const row={request_id:requestId,receipt_ref:receiptRef,command,source_revision:sourceRevision,request_sha256:requestSha,response_sha256:responseSha,receipt_sha256:receiptSha,receipt};rows.set(requestId,row);return{rows:[row]};}if(sql.includes('WHERE request_id = $1')){const row=rows.get(params[0]);return{rows:row?[row]:[]};}if(sql.includes('WHERE receipt_ref = $1')){const row=[...rows.values()].find(v=>v.receipt_ref===params[0]);return{rows:row?[row]:[]};}return{rows:[]};}};}
function handler(db,workerCommand){return createCloudRunHandler({db,runtime:{publishAndVerify:async()=>({})},workerCommand,semanticReceiptStore:createPostgresSemanticCommandReceiptStore(db,{now:()=> '2026-09-15T14:00:00.000Z'}),sourceRevision:SOURCE,authorityMode:'authoritative'});}

test('authoritative worker response is persisted and returned with digest-bound receipt headers',async()=>{const db=memoryDb();let calls=0;const h=handler(db,async()=>{calls+=1;return{status:200,body:{ok:true,command:'project.inspect',token:'secret'}};});const res=responseRecorder();const body=JSON.stringify({command:'project.inspect',input:{project_ref:'github:owner/repo'}});await h(await request({body,headers:{'x-overcenter-request-id':'req-1','x-overcenter-expected-head':SOURCE}}),res);assert.equal(res.statusCode,200);assert.equal(calls,1);const payload=JSON.parse(res.body);assert.equal(payload.ok,true);assert.equal(payload.command,'project.inspect');assert.equal(payload.authority_receipt.receipt_sha256,res.headers['x-overcenter-receipt-sha256']);assert.match(res.headers['x-overcenter-receipt-sha256'],/^[0-9a-f]{64}$/);assert.equal(res.headers['x-overcenter-source-revision'],SOURCE);assert.equal(db.rows.size,1);});

test('matching request id replays the authoritative receipt without re-executing semantic work',async()=>{const db=memoryDb();let calls=0;const h=handler(db,async()=>{calls+=1;return{status:200,body:{ok:true,calls}};});const body=JSON.stringify({command:'project.inspect',input:{project_ref:'github:owner/repo'}});for(let i=0;i<2;i++){const res=responseRecorder();await h(await request({body,headers:{'x-overcenter-request-id':'req-replay','x-overcenter-expected-head':SOURCE}}),res);assert.equal(res.statusCode,200);assert.equal(JSON.parse(res.body).calls,1);assert.equal(JSON.parse(res.body).authority_receipt.request_id,'req-replay');}assert.equal(calls,1);});

test('source revision mismatch fails before semantic work',async()=>{const db=memoryDb();let calls=0;const h=handler(db,async()=>{calls+=1;return{status:200,body:{ok:true}};});const res=responseRecorder();await h(await request({body:JSON.stringify({command:'project.inspect',input:{}}),headers:{'x-overcenter-request-id':'req-stale','x-overcenter-expected-head':'b'.repeat(40)}}),res);assert.equal(res.statusCode,409);assert.equal(JSON.parse(res.body).error,'SEMANTIC_RECEIPT_SOURCE_REVISION_MISMATCH');assert.equal(calls,0);assert.equal(db.rows.size,0);});

test('authoritative receipt endpoint verifies caller digest and returns durable response evidence',async()=>{const db=memoryDb();const h=handler(db,async()=>({status:200,body:{ok:true,value:7}}));const invoke=responseRecorder();const body=JSON.stringify({command:'project.inspect',input:{}});await h(await request({body,headers:{'x-overcenter-request-id':'req-read','x-overcenter-expected-head':SOURCE}}),invoke);const ref=invoke.headers['x-overcenter-receipt-ref'];const digest=invoke.headers['x-overcenter-receipt-sha256'];const read=responseRecorder();await h(await request({url:'/api/authoritative-state/semantic-receipt',body:JSON.stringify({receipt_ref:ref,expected_receipt_sha256:digest})}),read);assert.equal(read.statusCode,200);const payload=JSON.parse(read.body);assert.equal(payload.receipt.receipt_sha256,digest);assert.deepEqual(payload.receipt.response,{ok:true,value:7});});

test('receipt endpoint fails closed on digest mismatch',async()=>{const db=memoryDb();const h=handler(db,async()=>({status:200,body:{ok:true}}));const invoke=responseRecorder();await h(await request({body:JSON.stringify({command:'project.inspect',input:{}}),headers:{'x-overcenter-request-id':'req-mismatch','x-overcenter-expected-head':SOURCE}}),invoke);const read=responseRecorder();await h(await request({url:'/api/authoritative-state/semantic-receipt',body:JSON.stringify({receipt_ref:invoke.headers['x-overcenter-receipt-ref'],expected_receipt_sha256:'0'.repeat(64)})}),read);assert.equal(read.statusCode,409);assert.equal(JSON.parse(read.body).error,'SEMANTIC_RECEIPT_DIGEST_MISMATCH');});
