import assert from 'node:assert/strict';
import test from 'node:test';
import { createProjectTransitionSettlementCertificate, projectTransitionObligationFingerprint, replayProjectTransitionSettlementCertificate } from '../lib/project-transition-certificate-settlement.js';
const sha = (ch) => ch.repeat(40); const authority = Object.freeze({ kind:'github', repository:'owner/repo', revision:sha('a'), derivation:'overcenter-project-graph-v1' }); const project_ref = 'github:owner/repo';
function transition(overrides = {}) { return { id:'ship-feature', priority:10, requires:[], executor:{ kind:'agent', role:'implementation' }, phase_bindings:{}, execution_intent:{ schema:'project-execution-intent-v1', desired_outcome:'Ship the verified feature.', acceptance_evidence:[{ kind:'tests', requirement:'Focused tests pass.' },{ kind:'verification', requirement:'Exact authoritative verification passes.' }] }, ...overrides }; }
const evidence = Object.freeze([Object.freeze({ kind:'tests', ref:'github:owner/repo/actions/runs/10@' + sha('b') }),Object.freeze({ kind:'verification', ref:'github:owner/repo@' + sha('c') })]);
async function certificateFor(current = transition(), extra = {}) { return createProjectTransitionSettlementCertificate({ project_ref, transition:current, authority, evidence, ...extra }); }
const replay = (current, certificate, extra = {}) => replayProjectTransitionSettlementCertificate({ project_ref, transition:current, authority, certificate, ...extra });
test('valid current certificate replays deterministically and idempotently', async () => { const current = transition(); const certificate = await certificateFor(current); const first = await replay(current, certificate); const second = await replay(current, structuredClone(certificate)); assert.equal(first.certificate_ref, second.certificate_ref); assert.equal(first.obligation_fingerprint, await projectTransitionObligationFingerprint(current)); });
test('unrelated authority revision does not invalidate an unchanged obligation without revision-bound authority evidence', async () => { const current = transition(); const certificate = await certificateFor(current); const result = await replayProjectTransitionSettlementCertificate({ project_ref, transition:current, authority:{ ...authority, revision:sha('d') }, certificate }); assert.equal(result.obligation_fingerprint, await projectTransitionObligationFingerprint(current)); });
test('stale exact authority evidence cannot replay a certificate', async () => { const current = transition({ execution_intent:{ schema:'project-execution-intent-v1', desired_outcome:'Ship.', acceptance_evidence:[{kind:'authority',requirement:'Exact authority.'}] } }); const certificate = await certificateFor(current, { evidence:[{kind:'authority',ref:`github:${authority.repository}@${authority.revision}`}] }); await assert.rejects(replayProjectTransitionSettlementCertificate({ project_ref, transition:current, authority:{ ...authority, revision:sha('d') }, certificate }), (error) => error?.code === 'PROJECT_TRANSITION_CERTIFICATE_AUTHORITY_STALE'); });
test('candidate revision evidence cannot authorize completed settlement', async () => { await assert.rejects(createProjectTransitionSettlementCertificate({ project_ref, transition:transition({ execution_intent:{ schema:'project-execution-intent-v1', desired_outcome:'Ship.', acceptance_evidence:[{kind:'candidate_revision',requirement:'Candidate exists.'}] } }), authority, evidence:[{kind:'candidate_revision',ref:sha('e')}] }), (error) => error?.code === 'PROJECT_TRANSITION_CERTIFICATE_AUTHORITY_STALE'); });
test('unrelated graph amendment does not change a transition obligation identity', async () => { const current = transition(); const before = await projectTransitionObligationFingerprint(current); assert.ok(transition({ id:'other-work', priority:999 })); assert.equal(await projectTransitionObligationFingerprint(current), before); });
test('changed acceptance semantics invalidate a prior certificate', async () => { const original = transition(); const certificate = await certificateFor(original); const changed = transition({ execution_intent:{ ...original.execution_intent, desired_outcome:'Ship the verified feature with stronger semantics.' } }); await assert.rejects(replay(changed, certificate), (error) => error?.code === 'PROJECT_TRANSITION_CERTIFICATE_OBLIGATION_STALE'); });
test('changed dependency semantics invalidate a prior certificate', async () => { const original = transition(); const certificate = await certificateFor(original); const changed = transition({ requires:['prepare-feature'] }); await assert.rejects(replay(changed, certificate, { predecessor_certificates:[] }), (error) => ['PROJECT_TRANSITION_CERTIFICATE_OBLIGATION_STALE','PROJECT_TRANSITION_CERTIFICATE_PREREQUISITE_CLOSURE_INVALID'].includes(error?.code)); });
test('missing declared acceptance evidence fails closed before certificate creation', async () => { await assert.rejects(createProjectTransitionSettlementCertificate({ project_ref, transition:transition(), authority, evidence:[evidence[0]] }), (error) => error?.code === 'PROJECT_TRANSITION_CERTIFICATE_EVIDENCE_INCOMPLETE' && error?.details?.missing_kinds?.includes('verification')); });
test('predecessor closure is exact and certificate-addressed', async () => { const predecessorTransition = transition({ id:'prepare-feature', execution_intent:{ schema:'project-execution-intent-v1', desired_outcome:'Prepare.', acceptance_evidence:[{kind:'tests',requirement:'Pass.'}] } }); const predecessor = await createProjectTransitionSettlementCertificate({ project_ref, transition:predecessorTransition, authority, evidence:[{kind:'tests',ref:'run:prepare'}] }); const current = transition({ requires:['prepare-feature'] }); const certificate = await createProjectTransitionSettlementCertificate({ project_ref, transition:current, authority, evidence, predecessor_certificates:[predecessor], predecessor_transitions:[predecessorTransition] }); const replayResult = await replay(current, certificate, { predecessor_certificates:[predecessor], predecessor_transitions:[predecessorTransition] }); assert.equal(replayResult.certificate.prerequisites.length, 1); assert.match(replayResult.certificate.prerequisites[0].certificate_ref, /^sha256:[0-9a-f]{64}$/); });
test('missing prerequisite certificate fails closed', async () => { const current = transition({ requires:['prepare-feature'] }); await assert.rejects(createProjectTransitionSettlementCertificate({ project_ref, transition:current, authority, evidence, predecessor_certificates:[] }), (error) => error?.code === 'PROJECT_TRANSITION_CERTIFICATE_PREREQUISITE_CLOSURE_INVALID'); });
test('missing predecessor transition semantics fail closed even when a certificate exists', async () => { const predecessorTransition = transition({ id:'prepare-feature', execution_intent:{ schema:'project-execution-intent-v1', desired_outcome:'Prepare.', acceptance_evidence:[{kind:'tests',requirement:'Pass.'}] } }); const predecessor = await createProjectTransitionSettlementCertificate({ project_ref, transition:predecessorTransition, authority, evidence:[{kind:'tests',ref:'run:prepare'}] }); const current = transition({ requires:['prepare-feature'] }); await assert.rejects(createProjectTransitionSettlementCertificate({ project_ref, transition:current, authority, evidence, predecessor_certificates:[predecessor], predecessor_transitions:[] }), (error) => error?.code === 'PROJECT_TRANSITION_CERTIFICATE_PREREQUISITE_CLOSURE_INVALID'); });
test('changed predecessor semantics invalidate predecessor closure', async () => { const predecessorTransition = transition({ id:'prepare-feature', execution_intent:{ schema:'project-execution-intent-v1', desired_outcome:'Prepare.', acceptance_evidence:[{kind:'tests',requirement:'Pass.'}] } }); const predecessor = await createProjectTransitionSettlementCertificate({ project_ref, transition:predecessorTransition, authority, evidence:[{kind:'tests',ref:'run:prepare'}] }); const changedPredecessor = transition({ ...predecessorTransition, execution_intent:{ ...predecessorTransition.execution_intent, desired_outcome:'Prepare with stronger semantics.' } }); const current = transition({ requires:['prepare-feature'] }); await assert.rejects(createProjectTransitionSettlementCertificate({ project_ref, transition:current, authority, evidence, predecessor_certificates:[predecessor], predecessor_transitions:[changedPredecessor] }), (error) => error?.code === 'PROJECT_TRANSITION_CERTIFICATE_PREREQUISITE_CLOSURE_INVALID'); });
test('certificate subject cannot be replayed for another transition', async () => { const current = transition(); const certificate = await certificateFor(current); await assert.rejects(replay(transition({ id:'other-transition' }), certificate), (error) => error?.code === 'PROJECT_TRANSITION_CERTIFICATE_SUBJECT_STALE'); });
