import test from 'node:test';
import assert from 'node:assert/strict';
import { register } from 'node:module';
register('./node-lib-alias-loader.mjs', import.meta.url);
const { applyGithubChangeset } = await import('../lib/github-apply-changeset.js');
const sha=n=>Number(n).toString(16).padStart(40,'0');
class Receipts{constructor(){this.rows=new Map();}key(n){return `${n.repo}#${n.idempotency_key}`;}async claim(n,d,t){const k=this.key(n),e=this.rows.get(k);if(e){if(e.request_sha256!==d)return{kind:'conflict',row:e};if(['succeeded','prepared'].includes(e.state))return{kind:'existing',row:e};return{kind:'in_progress',row:e};}const r={repo:n.repo,idempotency_key:n.idempotency_key,request_sha256:d,state:'processing',attempt_token:t,branch:n.branch};this.rows.set(k,r);return{kind:'claimed',row:r};}async findSucceededByCommit(repo,branch,commitSha){return [...this.rows.values()].find(r=>r.repo===repo&&r.branch===branch&&r.commit_sha===commitSha&&r.state==='succeeded')||null;}async savePlan(n,t,p){Object.assign(this.rows.get(this.key(n)),{base_sha:p.baseSha,old_head:p.oldHead,created_branch:p.createdBranch,precondition_verified:p.preconditionVerified,changed_paths:p.changedPaths});}async heartbeat(){return true;}async saveTree(n,t,x){this.rows.get(this.key(n)).tree_sha=x;}async saveCommit(n,t,x){Object.assign(this.rows.get(this.key(n)),{commit_sha:x,state:'prepared'});}async succeed(n,t,x){Object.assign(this.rows.get(this.key(n)),{state:'succeeded',receipt:x});return true;}async abandon(n){this.rows.delete(this.key(n));}}
class Github{constructor(){this.main=sha(1);this.seq=10;this.forceUpdates=[];const tree=sha(2);this.trees=new Map([[tree,new Map([['f.txt',{path:'f.txt',mode:'100644',type:'blob',sha:sha(3),content:'base\n'}]])]]);this.commits=new Map([[this.main,{sha:this.main,tree_sha:tree,message:'base',parents:[]}]]);this.branches=new Map([['main',this.main],['work/existing',this.main]]);}async resolveCommit(r,s){const id=this.branches.get(s)||s,c=this.commits.get(id);return{sha:c.sha,tree_sha:c.tree_sha};}async getBranch(r,b){return this.branches.has(b)?{sha:this.branches.get(b)}:null;}async getCommit(r,id){return{...this.commits.get(id)};}async getPathEntries(r,t,p){const e=this.trees.get(t)||new Map();return new Map(p.map(x=>[x,e.get(x)||null]));}async createTree(r,b,entries){const n=new Map(this.trees.get(b)||[]);for(const e of entries){if(e.sha===null)n.delete(e.path);else n.set(e.path,{...e,sha:sha(++this.seq)});}const id=sha(++this.seq);this.trees.set(id,n);return id;}async createCommit(r,{message,treeSha,parentSha}){const id=sha(++this.seq);this.commits.set(id,{sha:id,tree_sha:treeSha,message,parents:[parentSha]});return id;}async createBranch(r,b,id){this.branches.set(b,id);}async updateBranch(r,b,id,o={}){this.forceUpdates.push(o.force===true);this.branches.set(b,id);}}
const request=(key,message,content,coalesce=false)=>({repo:'laurajoyhutchins/overcenter',base_ref:'main',branch:'work/existing',expected_head:null,changes:[{path:'f.txt',operation:'update',content}],commit_message:message,idempotency_key:key,...(coalesce?{coalesce_mechanical_head:true}:{})});
const authority={require:async()=>({subject:'project_transition',lease_id:'lease-1'})};
test('blocked mechanical follow-up advertises executable recovery',async()=>{const github=new Github(),receipts=new Receipts();const first=await applyGithubChangeset(request('one','style: first cleanup','first\n'),{github,receipts,executionAuthority:authority,idFactory:()=>sha(1)});const blocked=await applyGithubChangeset({...request('two','style: final newline','second\n'),expected_head:first.new_head},{github,receipts,executionAuthority:authority,idFactory:()=>sha(2)});assert.equal(blocked.error,'MECHANICAL_CHANGESET_MUST_COALESCE');assert.deepEqual(blocked.recovery_operation,{command:'github.apply_changeset',set:{coalesce_mechanical_head:true}});});
test('same-lease coalescing replaces exact mechanical head and replay is idempotent',async()=>{const github=new Github(),receipts=new Receipts();const first=await applyGithubChangeset(request('one','style: first cleanup','first\n'),{github,receipts,executionAuthority:authority,idFactory:()=>sha(1)});const input={...request('two','style: final newline','second\n',true),expected_head:first.new_head};const combined=await applyGithubChangeset(input,{github,receipts,executionAuthority:authority,idFactory:()=>sha(2)});assert.equal(combined.ok,true);assert.equal(github.forceUpdates.at(-1),true);assert.deepEqual(github.commits.get(combined.new_head).parents,[github.main]);const replay=await applyGithubChangeset(input,{github,receipts,executionAuthority:authority,idFactory:()=>sha(3)});assert.equal(replay.idempotent_replay,true);});